//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OpenRepairOrderLookupResponse {
    
    private OpenRepairOrderLookupResponseOpenRepairOrder[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OpenRepairOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OpenRepairOrderLookupResponseOpenRepairOrder[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class OpenRepairOrderLookupResponseOpenRepairOrder {
    
    private string companyNumberField;
    
    private string internalKeyField;
    
    private string counterPersonIDField;
    
    private string recordStatusField;
    
    private string documentTypeField;
    
    private string transactionTypeField;
    
    private string openTransactionDateField;
    
    private string repairOrderNumberField;
    
    private string customerNumberField;
    
    private string customerKeyField;
    
    private string customerNameField;
    
    private string customerPhoneNumberField;
    
    private string customerAddress1Field;
    
    private string customerAddress2Field;
    
    private string customerCityField;
    
    private string customerStateField;
    
    private string customerZipCodeField;
    
    private string customerEmailField;
    
    private string shipToKeyField;
    
    private string paymentMethodField;
    
    private string saleTypeField;
    
    private string priceLevelField;
    
    private string taxExemptField;
    
    private string partsTotalField;
    
    private string shippingTotalField;
    
    private string specialOrderDepositField;
    
    private string specialOrderDepositCRField;
    
    private string specialOrderDepositPercentField;
    
    private string specialOrderDepositOverrideField;
    
    private string specialOrderOnHoldField;
    
    private string partsSalesTax1Field;
    
    private string partsSalesTax2Field;
    
    private string partsSalesTax3Field;
    
    private string partsSalesTax4Field;
    
    private string counterPersonNameField;
    
    private string sortKeyField;
    
    private string authorizeCounterPersonIDField;
    
    private string creditCardARCustomerNumberField;
    
    private string purchaseOrderNumberField;
    
    private string receiptNumberField;
    
    private string originalDocNumberField;
    
    private string internalAccountNumberField;
    
    private string rOTypeField;
    
    private string rOStatusField;
    
    private string warrantyROField;
    
    private string partsApprovedField;
    
    private string serviceApprovedField;
    
    private string serviceWriterIDField;
    
    private string rOTechnicianIDField;
    
    private string totalEstimateField;
    
    private string serviceContractCompField;
    
    private string serviceContractComp2Field;
    
    private string serviceContractDeductField;
    
    private string serviceContractDeduct2Field;
    
    private string warrantyDeductField;
    
    private string vINField;
    
    private string stockNumberField;
    
    private string makeField;
    
    private string modelField;
    
    private string modelYearField;
    
    private string truckField;
    
    private string franchiseCodeField;
    
    private string odometerInField;
    
    private string odometerOutField;
    
    private string timeInField;
    
    private string promisedDateTimeField;
    
    private string remainingTimeField;
    
    private string tagNumberField;
    
    private string checkNumberField;
    
    private string headerCommentsField;
    
    private string shopSupplyOverrideField;
    
    private string hazardousMaterialOverrideField;
    
    private string laborTotalField;
    
    private string subletTotalField;
    
    private string sCDeductPaidField;
    
    private string customerPayHazardousMaterialField;
    
    private string customerPayTax1Field;
    
    private string customerPayTax2Field;
    
    private string customerPayTax3Field;
    
    private string customerPayTax4Field;
    
    private string warrantyTax1Field;
    
    private string warrantyTax2Field;
    
    private string warrantyTax3Field;
    
    private string warrantyTax4Field;
    
    private string internalTax1Field;
    
    private string internalTax2Field;
    
    private string internalTax3Field;
    
    private string internalTax4Field;
    
    private string serviceContractTax1Field;
    
    private string serviceContractTax2Field;
    
    private string serviceContractTax3Field;
    
    private string serviceContractTax4Field;
    
    private string customerPayShopSupField;
    
    private string warrantyShopSupField;
    
    private string internalShopSupField;
    
    private string serviceContractShopSupField;
    
    private string couponNumberField;
    
    private string couponDiscountField;
    
    private string totalCouponDiscountField;
    
    private string paidByManufacturerField;
    
    private string paidByDealerField;
    
    private string customerPayTotalDueField;
    
    private string orderStatusField;
    
    private string dateToArriveField;
    
    private string aRCustomerKeyField;
    
    private string warrantyRONumberField;
    
    private string workStationIDField;
    
    private string internalAuthorizedByField;
    
    private string appointmentDateTimeField;
    
    private string dateTimeLastLineCompleteField;
    
    private string dateTimePreInvoicedField;
    
    private string internalPayTypeField;
    
    private string repairOrderPriorityField;
    
    private string dailyRentalAgreementNumberField;
    
    private string towedInIndicatorField;
    
    private string lastModifiedField;
    
    private OpenRepairOrderLookupResponseOpenRepairOrderDetailsOpenRepairOrderDetail[][] detailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompanyNumber {
        get {
            return this.companyNumberField;
        }
        set {
            this.companyNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalKey {
        get {
            return this.internalKeyField;
        }
        set {
            this.internalKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CounterPersonID {
        get {
            return this.counterPersonIDField;
        }
        set {
            this.counterPersonIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecordStatus {
        get {
            return this.recordStatusField;
        }
        set {
            this.recordStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OpenTransactionDate {
        get {
            return this.openTransactionDateField;
        }
        set {
            this.openTransactionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RepairOrderNumber {
        get {
            return this.repairOrderNumberField;
        }
        set {
            this.repairOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerKey {
        get {
            return this.customerKeyField;
        }
        set {
            this.customerKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPhoneNumber {
        get {
            return this.customerPhoneNumberField;
        }
        set {
            this.customerPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerAddress1 {
        get {
            return this.customerAddress1Field;
        }
        set {
            this.customerAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerAddress2 {
        get {
            return this.customerAddress2Field;
        }
        set {
            this.customerAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerCity {
        get {
            return this.customerCityField;
        }
        set {
            this.customerCityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerState {
        get {
            return this.customerStateField;
        }
        set {
            this.customerStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerZipCode {
        get {
            return this.customerZipCodeField;
        }
        set {
            this.customerZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerEmail {
        get {
            return this.customerEmailField;
        }
        set {
            this.customerEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShipToKey {
        get {
            return this.shipToKeyField;
        }
        set {
            this.shipToKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaymentMethod {
        get {
            return this.paymentMethodField;
        }
        set {
            this.paymentMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SaleType {
        get {
            return this.saleTypeField;
        }
        set {
            this.saleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceLevel {
        get {
            return this.priceLevelField;
        }
        set {
            this.priceLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxExempt {
        get {
            return this.taxExemptField;
        }
        set {
            this.taxExemptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsTotal {
        get {
            return this.partsTotalField;
        }
        set {
            this.partsTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingTotal {
        get {
            return this.shippingTotalField;
        }
        set {
            this.shippingTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderDeposit {
        get {
            return this.specialOrderDepositField;
        }
        set {
            this.specialOrderDepositField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderDepositCR {
        get {
            return this.specialOrderDepositCRField;
        }
        set {
            this.specialOrderDepositCRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderDepositPercent {
        get {
            return this.specialOrderDepositPercentField;
        }
        set {
            this.specialOrderDepositPercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderDepositOverride {
        get {
            return this.specialOrderDepositOverrideField;
        }
        set {
            this.specialOrderDepositOverrideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderOnHold {
        get {
            return this.specialOrderOnHoldField;
        }
        set {
            this.specialOrderOnHoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsSalesTax1 {
        get {
            return this.partsSalesTax1Field;
        }
        set {
            this.partsSalesTax1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsSalesTax2 {
        get {
            return this.partsSalesTax2Field;
        }
        set {
            this.partsSalesTax2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsSalesTax3 {
        get {
            return this.partsSalesTax3Field;
        }
        set {
            this.partsSalesTax3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsSalesTax4 {
        get {
            return this.partsSalesTax4Field;
        }
        set {
            this.partsSalesTax4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CounterPersonName {
        get {
            return this.counterPersonNameField;
        }
        set {
            this.counterPersonNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortKey {
        get {
            return this.sortKeyField;
        }
        set {
            this.sortKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthorizeCounterPersonID {
        get {
            return this.authorizeCounterPersonIDField;
        }
        set {
            this.authorizeCounterPersonIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditCardARCustomerNumber {
        get {
            return this.creditCardARCustomerNumberField;
        }
        set {
            this.creditCardARCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PurchaseOrderNumber {
        get {
            return this.purchaseOrderNumberField;
        }
        set {
            this.purchaseOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReceiptNumber {
        get {
            return this.receiptNumberField;
        }
        set {
            this.receiptNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OriginalDocNumber {
        get {
            return this.originalDocNumberField;
        }
        set {
            this.originalDocNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalAccountNumber {
        get {
            return this.internalAccountNumberField;
        }
        set {
            this.internalAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ROType {
        get {
            return this.rOTypeField;
        }
        set {
            this.rOTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ROStatus {
        get {
            return this.rOStatusField;
        }
        set {
            this.rOStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyRO {
        get {
            return this.warrantyROField;
        }
        set {
            this.warrantyROField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsApproved {
        get {
            return this.partsApprovedField;
        }
        set {
            this.partsApprovedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceApproved {
        get {
            return this.serviceApprovedField;
        }
        set {
            this.serviceApprovedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceWriterID {
        get {
            return this.serviceWriterIDField;
        }
        set {
            this.serviceWriterIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ROTechnicianID {
        get {
            return this.rOTechnicianIDField;
        }
        set {
            this.rOTechnicianIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalEstimate {
        get {
            return this.totalEstimateField;
        }
        set {
            this.totalEstimateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractComp {
        get {
            return this.serviceContractCompField;
        }
        set {
            this.serviceContractCompField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractComp2 {
        get {
            return this.serviceContractComp2Field;
        }
        set {
            this.serviceContractComp2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractDeduct {
        get {
            return this.serviceContractDeductField;
        }
        set {
            this.serviceContractDeductField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractDeduct2 {
        get {
            return this.serviceContractDeduct2Field;
        }
        set {
            this.serviceContractDeduct2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyDeduct {
        get {
            return this.warrantyDeductField;
        }
        set {
            this.warrantyDeductField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VIN {
        get {
            return this.vINField;
        }
        set {
            this.vINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StockNumber {
        get {
            return this.stockNumberField;
        }
        set {
            this.stockNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Make {
        get {
            return this.makeField;
        }
        set {
            this.makeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ModelYear {
        get {
            return this.modelYearField;
        }
        set {
            this.modelYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Truck {
        get {
            return this.truckField;
        }
        set {
            this.truckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FranchiseCode {
        get {
            return this.franchiseCodeField;
        }
        set {
            this.franchiseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OdometerIn {
        get {
            return this.odometerInField;
        }
        set {
            this.odometerInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OdometerOut {
        get {
            return this.odometerOutField;
        }
        set {
            this.odometerOutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeIn {
        get {
            return this.timeInField;
        }
        set {
            this.timeInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PromisedDateTime {
        get {
            return this.promisedDateTimeField;
        }
        set {
            this.promisedDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RemainingTime {
        get {
            return this.remainingTimeField;
        }
        set {
            this.remainingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TagNumber {
        get {
            return this.tagNumberField;
        }
        set {
            this.tagNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CheckNumber {
        get {
            return this.checkNumberField;
        }
        set {
            this.checkNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeaderComments {
        get {
            return this.headerCommentsField;
        }
        set {
            this.headerCommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShopSupplyOverride {
        get {
            return this.shopSupplyOverrideField;
        }
        set {
            this.shopSupplyOverrideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HazardousMaterialOverride {
        get {
            return this.hazardousMaterialOverrideField;
        }
        set {
            this.hazardousMaterialOverrideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborTotal {
        get {
            return this.laborTotalField;
        }
        set {
            this.laborTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubletTotal {
        get {
            return this.subletTotalField;
        }
        set {
            this.subletTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SCDeductPaid {
        get {
            return this.sCDeductPaidField;
        }
        set {
            this.sCDeductPaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayHazardousMaterial {
        get {
            return this.customerPayHazardousMaterialField;
        }
        set {
            this.customerPayHazardousMaterialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayTax1 {
        get {
            return this.customerPayTax1Field;
        }
        set {
            this.customerPayTax1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayTax2 {
        get {
            return this.customerPayTax2Field;
        }
        set {
            this.customerPayTax2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayTax3 {
        get {
            return this.customerPayTax3Field;
        }
        set {
            this.customerPayTax3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayTax4 {
        get {
            return this.customerPayTax4Field;
        }
        set {
            this.customerPayTax4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyTax1 {
        get {
            return this.warrantyTax1Field;
        }
        set {
            this.warrantyTax1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyTax2 {
        get {
            return this.warrantyTax2Field;
        }
        set {
            this.warrantyTax2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyTax3 {
        get {
            return this.warrantyTax3Field;
        }
        set {
            this.warrantyTax3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyTax4 {
        get {
            return this.warrantyTax4Field;
        }
        set {
            this.warrantyTax4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalTax1 {
        get {
            return this.internalTax1Field;
        }
        set {
            this.internalTax1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalTax2 {
        get {
            return this.internalTax2Field;
        }
        set {
            this.internalTax2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalTax3 {
        get {
            return this.internalTax3Field;
        }
        set {
            this.internalTax3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalTax4 {
        get {
            return this.internalTax4Field;
        }
        set {
            this.internalTax4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractTax1 {
        get {
            return this.serviceContractTax1Field;
        }
        set {
            this.serviceContractTax1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractTax2 {
        get {
            return this.serviceContractTax2Field;
        }
        set {
            this.serviceContractTax2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractTax3 {
        get {
            return this.serviceContractTax3Field;
        }
        set {
            this.serviceContractTax3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractTax4 {
        get {
            return this.serviceContractTax4Field;
        }
        set {
            this.serviceContractTax4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayShopSup {
        get {
            return this.customerPayShopSupField;
        }
        set {
            this.customerPayShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyShopSup {
        get {
            return this.warrantyShopSupField;
        }
        set {
            this.warrantyShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalShopSup {
        get {
            return this.internalShopSupField;
        }
        set {
            this.internalShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractShopSup {
        get {
            return this.serviceContractShopSupField;
        }
        set {
            this.serviceContractShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponNumber {
        get {
            return this.couponNumberField;
        }
        set {
            this.couponNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponDiscount {
        get {
            return this.couponDiscountField;
        }
        set {
            this.couponDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalCouponDiscount {
        get {
            return this.totalCouponDiscountField;
        }
        set {
            this.totalCouponDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaidByManufacturer {
        get {
            return this.paidByManufacturerField;
        }
        set {
            this.paidByManufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaidByDealer {
        get {
            return this.paidByDealerField;
        }
        set {
            this.paidByDealerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayTotalDue {
        get {
            return this.customerPayTotalDueField;
        }
        set {
            this.customerPayTotalDueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateToArrive {
        get {
            return this.dateToArriveField;
        }
        set {
            this.dateToArriveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ARCustomerKey {
        get {
            return this.aRCustomerKeyField;
        }
        set {
            this.aRCustomerKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyRONumber {
        get {
            return this.warrantyRONumberField;
        }
        set {
            this.warrantyRONumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkStationID {
        get {
            return this.workStationIDField;
        }
        set {
            this.workStationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalAuthorizedBy {
        get {
            return this.internalAuthorizedByField;
        }
        set {
            this.internalAuthorizedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppointmentDateTime {
        get {
            return this.appointmentDateTimeField;
        }
        set {
            this.appointmentDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateTimeLastLineComplete {
        get {
            return this.dateTimeLastLineCompleteField;
        }
        set {
            this.dateTimeLastLineCompleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateTimePreInvoiced {
        get {
            return this.dateTimePreInvoicedField;
        }
        set {
            this.dateTimePreInvoicedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalPayType {
        get {
            return this.internalPayTypeField;
        }
        set {
            this.internalPayTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RepairOrderPriority {
        get {
            return this.repairOrderPriorityField;
        }
        set {
            this.repairOrderPriorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DailyRentalAgreementNumber {
        get {
            return this.dailyRentalAgreementNumberField;
        }
        set {
            this.dailyRentalAgreementNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TowedInIndicator {
        get {
            return this.towedInIndicatorField;
        }
        set {
            this.towedInIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OpenRepairOrderDetail", typeof(OpenRepairOrderLookupResponseOpenRepairOrderDetailsOpenRepairOrderDetail), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public OpenRepairOrderLookupResponseOpenRepairOrderDetailsOpenRepairOrderDetail[][] Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class OpenRepairOrderLookupResponseOpenRepairOrderDetailsOpenRepairOrderDetail {
    
    private string serviceLineNoField;
    
    private string lineTypeField;
    
    private string sequenceNumberField;
    
    private string counterPersonIDField;
    
    private string transCodeField;
    
    private string specialOrderEmergencyPurchaseField;
    
    private string transDateField;
    
    private string manufacturerField;
    
    private string partNumberField;
    
    private string partNoLengthField;
    
    private string stockGroupField;
    
    private string binLocationField;
    
    private string quantityField;
    
    private string costField;
    
    private string listPriceField;
    
    private string tradePriceField;
    
    private string flatPriceField;
    
    private string netPriceField;
    
    private string bookListField;
    
    private string priceMethodField;
    
    private string pricePercentField;
    
    private string priceBaseField;
    
    private string specialCodeField;
    
    private string priceOverrideField;
    
    private string groupPriceField;
    
    private string isCorePartField;
    
    private string addNSPartField;
    
    private string specialOrderPriorityField;
    
    private string originalSpecialOrderField;
    
    private string excludeFromHistoryField;
    
    private string commentsField;
    
    private string lineStatusField;
    
    private string serviceTypeField;
    
    private string linePaymentMethodField;
    
    private string policyAdjustmentField;
    
    private string technicianIDField;
    
    private string laborOpCodeField;
    
    private string correctionLaborOpCodeField;
    
    private string laborHoursField;
    
    private string laborCostHoursField;
    
    private string actualRetailAmountField;
    
    private string failureCodeField;
    
    private string priceLevelField;
    
    private string priceStrategyAssignmentField;
    
    private string subletVendorNumberField;
    
    private string subletInvoiceNumberField;
    
    private string couponNumberField;
    
    private string factoryLaborHoursField;
    
    private string authorizationCodeField;
    
    private string batteryWarrantyCodeField;
    
    private string dateTimeLineCompletedField;
    
    private string internalAccountField;
    
    private string authorizerField;
    
    private string netItemTotalField;
    
    private string administrativeLaborAmountField;
    
    private string administrativeHoursField;
    
    private string paintAndMaterialsCostField;
    
    private string paintAndMaterialsRetailField;
    
    private string repeatRepairFlagField;
    
    private string taxableInternalLineField;
    
    private string upsellFlagField;
    
    private string warrantyClaimTypeField;
    
    private string vATCodeField;
    
    private string vATAmountField;
    
    private string returnToInventoryFlagField;
    
    private string skillLevelField;
    
    private string oEMReplacementFlagField;
    
    private string costDifferentialField;
    
    private string optionSequenceNumberField;
    
    private string dispatchStartTimeField;
    
    private string totalDiscountLaborField;
    
    private string totalDiscountPartsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceLineNo {
        get {
            return this.serviceLineNoField;
        }
        set {
            this.serviceLineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineType {
        get {
            return this.lineTypeField;
        }
        set {
            this.lineTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CounterPersonID {
        get {
            return this.counterPersonIDField;
        }
        set {
            this.counterPersonIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransCode {
        get {
            return this.transCodeField;
        }
        set {
            this.transCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderEmergencyPurchase {
        get {
            return this.specialOrderEmergencyPurchaseField;
        }
        set {
            this.specialOrderEmergencyPurchaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransDate {
        get {
            return this.transDateField;
        }
        set {
            this.transDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartNumber {
        get {
            return this.partNumberField;
        }
        set {
            this.partNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartNoLength {
        get {
            return this.partNoLengthField;
        }
        set {
            this.partNoLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StockGroup {
        get {
            return this.stockGroupField;
        }
        set {
            this.stockGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BinLocation {
        get {
            return this.binLocationField;
        }
        set {
            this.binLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ListPrice {
        get {
            return this.listPriceField;
        }
        set {
            this.listPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TradePrice {
        get {
            return this.tradePriceField;
        }
        set {
            this.tradePriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FlatPrice {
        get {
            return this.flatPriceField;
        }
        set {
            this.flatPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetPrice {
        get {
            return this.netPriceField;
        }
        set {
            this.netPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BookList {
        get {
            return this.bookListField;
        }
        set {
            this.bookListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceMethod {
        get {
            return this.priceMethodField;
        }
        set {
            this.priceMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PricePercent {
        get {
            return this.pricePercentField;
        }
        set {
            this.pricePercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceBase {
        get {
            return this.priceBaseField;
        }
        set {
            this.priceBaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialCode {
        get {
            return this.specialCodeField;
        }
        set {
            this.specialCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceOverride {
        get {
            return this.priceOverrideField;
        }
        set {
            this.priceOverrideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GroupPrice {
        get {
            return this.groupPriceField;
        }
        set {
            this.groupPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsCorePart {
        get {
            return this.isCorePartField;
        }
        set {
            this.isCorePartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AddNSPart {
        get {
            return this.addNSPartField;
        }
        set {
            this.addNSPartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderPriority {
        get {
            return this.specialOrderPriorityField;
        }
        set {
            this.specialOrderPriorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OriginalSpecialOrder {
        get {
            return this.originalSpecialOrderField;
        }
        set {
            this.originalSpecialOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExcludeFromHistory {
        get {
            return this.excludeFromHistoryField;
        }
        set {
            this.excludeFromHistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineStatus {
        get {
            return this.lineStatusField;
        }
        set {
            this.lineStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LinePaymentMethod {
        get {
            return this.linePaymentMethodField;
        }
        set {
            this.linePaymentMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PolicyAdjustment {
        get {
            return this.policyAdjustmentField;
        }
        set {
            this.policyAdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TechnicianID {
        get {
            return this.technicianIDField;
        }
        set {
            this.technicianIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborOpCode {
        get {
            return this.laborOpCodeField;
        }
        set {
            this.laborOpCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CorrectionLaborOpCode {
        get {
            return this.correctionLaborOpCodeField;
        }
        set {
            this.correctionLaborOpCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborHours {
        get {
            return this.laborHoursField;
        }
        set {
            this.laborHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborCostHours {
        get {
            return this.laborCostHoursField;
        }
        set {
            this.laborCostHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActualRetailAmount {
        get {
            return this.actualRetailAmountField;
        }
        set {
            this.actualRetailAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailureCode {
        get {
            return this.failureCodeField;
        }
        set {
            this.failureCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceLevel {
        get {
            return this.priceLevelField;
        }
        set {
            this.priceLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceStrategyAssignment {
        get {
            return this.priceStrategyAssignmentField;
        }
        set {
            this.priceStrategyAssignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubletVendorNumber {
        get {
            return this.subletVendorNumberField;
        }
        set {
            this.subletVendorNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubletInvoiceNumber {
        get {
            return this.subletInvoiceNumberField;
        }
        set {
            this.subletInvoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponNumber {
        get {
            return this.couponNumberField;
        }
        set {
            this.couponNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FactoryLaborHours {
        get {
            return this.factoryLaborHoursField;
        }
        set {
            this.factoryLaborHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthorizationCode {
        get {
            return this.authorizationCodeField;
        }
        set {
            this.authorizationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BatteryWarrantyCode {
        get {
            return this.batteryWarrantyCodeField;
        }
        set {
            this.batteryWarrantyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateTimeLineCompleted {
        get {
            return this.dateTimeLineCompletedField;
        }
        set {
            this.dateTimeLineCompletedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalAccount {
        get {
            return this.internalAccountField;
        }
        set {
            this.internalAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Authorizer {
        get {
            return this.authorizerField;
        }
        set {
            this.authorizerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetItemTotal {
        get {
            return this.netItemTotalField;
        }
        set {
            this.netItemTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdministrativeLaborAmount {
        get {
            return this.administrativeLaborAmountField;
        }
        set {
            this.administrativeLaborAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdministrativeHours {
        get {
            return this.administrativeHoursField;
        }
        set {
            this.administrativeHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaintAndMaterialsCost {
        get {
            return this.paintAndMaterialsCostField;
        }
        set {
            this.paintAndMaterialsCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaintAndMaterialsRetail {
        get {
            return this.paintAndMaterialsRetailField;
        }
        set {
            this.paintAndMaterialsRetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RepeatRepairFlag {
        get {
            return this.repeatRepairFlagField;
        }
        set {
            this.repeatRepairFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxableInternalLine {
        get {
            return this.taxableInternalLineField;
        }
        set {
            this.taxableInternalLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UpsellFlag {
        get {
            return this.upsellFlagField;
        }
        set {
            this.upsellFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyClaimType {
        get {
            return this.warrantyClaimTypeField;
        }
        set {
            this.warrantyClaimTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATCode {
        get {
            return this.vATCodeField;
        }
        set {
            this.vATCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATAmount {
        get {
            return this.vATAmountField;
        }
        set {
            this.vATAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReturnToInventoryFlag {
        get {
            return this.returnToInventoryFlagField;
        }
        set {
            this.returnToInventoryFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SkillLevel {
        get {
            return this.skillLevelField;
        }
        set {
            this.skillLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OEMReplacementFlag {
        get {
            return this.oEMReplacementFlagField;
        }
        set {
            this.oEMReplacementFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CostDifferential {
        get {
            return this.costDifferentialField;
        }
        set {
            this.costDifferentialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OptionSequenceNumber {
        get {
            return this.optionSequenceNumberField;
        }
        set {
            this.optionSequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DispatchStartTime {
        get {
            return this.dispatchStartTimeField;
        }
        set {
            this.dispatchStartTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalDiscountLabor {
        get {
            return this.totalDiscountLaborField;
        }
        set {
            this.totalDiscountLaborField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalDiscountParts {
        get {
            return this.totalDiscountPartsField;
        }
        set {
            this.totalDiscountPartsField = value;
        }
    }
}
