//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTrack.References {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="opentrack.dealertrack.com", ConfigurationName="References.ServiceAPISoap")]
    public interface ServiceAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="opentrack.dealertrack.com/GetClosedRepairOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OpenTrack.References.GetClosedRepairOrdersResponse GetClosedRepairOrders(OpenTrack.References.DealerInfo dealer, OpenTrack.References.GetClosedRepairOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="opentrack.dealertrack.com/GetClosedRepairOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OpenTrack.References.GetClosedRepairOrderDetailResponse GetClosedRepairOrderDetails(OpenTrack.References.DealerInfo dealer, OpenTrack.References.GetClosedRepairOrderDetailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class DealerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyNumberField;
        
        private string enterpriseCodeField;
        
        private string serverNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
                this.RaisePropertyChanged("CompanyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EnterpriseCode {
            get {
                return this.enterpriseCodeField;
            }
            set {
                this.enterpriseCodeField = value;
                this.RaisePropertyChanged("EnterpriseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
                this.RaisePropertyChanged("ServerName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class GetClosedRepairOrderDetailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClosedRepairOrder closedRepairOrderField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClosedRepairOrder ClosedRepairOrder {
            get {
                return this.closedRepairOrderField;
            }
            set {
                this.closedRepairOrderField = value;
                this.RaisePropertyChanged("ClosedRepairOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class ClosedRepairOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyNumberField;
        
        private string repairOrderNumberField;
        
        private string repairOrderTypeField;
        
        private string warrantyRONumberField;
        
        private string serviceWriterIDField;
        
        private string rOTechnicianIDField;
        
        private string customerKeyField;
        
        private string customerNameField;
        
        private string customerPhoneNumberField;
        
        private string customerAddress1Field;
        
        private string customerAddress2Field;
        
        private string customerCityField;
        
        private string customerStateField;
        
        private string customerZipCodeField;
        
        private string aRCustomerKeyField;
        
        private string paymentMethodField;
        
        private string openDateField;
        
        private string closeDateField;
        
        private string finalCloseDateField;
        
        private string vINField;
        
        private string totalEstimateField;
        
        private string serviceContractCompField;
        
        private string serviceContractComp2Field;
        
        private string serviceContractDeductField;
        
        private string serviceContractDeduct2Field;
        
        private string warrantyDeductField;
        
        private string franchiseCodeField;
        
        private string odometerInField;
        
        private string odometerOutField;
        
        private string checkNumberField;
        
        private string purchaseOrderNumberField;
        
        private string receiptNumberField;
        
        private string partsTotalField;
        
        private string laborTotalField;
        
        private string subletTotalField;
        
        private string serviceContractDeductPaidField;
        
        private string serviceContractTotalField;
        
        private string specialOrderDepositsField;
        
        private string customerPayHazardousMaterialsField;
        
        private string customerPaySaleTaxField;
        
        private string warrantySaleTaxField;
        
        private string internalSaleTaxField;
        
        private string serviceContractSaleTaxField;
        
        private string customerPayShopSupField;
        
        private string warrantyShopSupField;
        
        private string internalShopSupField;
        
        private string serviceContractShopSupField;
        
        private string couponNumberField;
        
        private string couponDiscountField;
        
        private string totalCouponDiscountField;
        
        private string totalSaleField;
        
        private string totalGrossField;
        
        private string internalAuthByField;
        
        private string tagNumberField;
        
        private string dateTimeOfAppointmentField;
        
        private string dateTimeLastLineCompleteField;
        
        private string dateTimePreInvoicedField;
        
        private string towedInIndicatorField;
        
        private ClosedRepairOrderDetail[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
                this.RaisePropertyChanged("CompanyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RepairOrderNumber {
            get {
                return this.repairOrderNumberField;
            }
            set {
                this.repairOrderNumberField = value;
                this.RaisePropertyChanged("RepairOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RepairOrderType {
            get {
                return this.repairOrderTypeField;
            }
            set {
                this.repairOrderTypeField = value;
                this.RaisePropertyChanged("RepairOrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string WarrantyRONumber {
            get {
                return this.warrantyRONumberField;
            }
            set {
                this.warrantyRONumberField = value;
                this.RaisePropertyChanged("WarrantyRONumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ServiceWriterID {
            get {
                return this.serviceWriterIDField;
            }
            set {
                this.serviceWriterIDField = value;
                this.RaisePropertyChanged("ServiceWriterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ROTechnicianID {
            get {
                return this.rOTechnicianIDField;
            }
            set {
                this.rOTechnicianIDField = value;
                this.RaisePropertyChanged("ROTechnicianID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerKey {
            get {
                return this.customerKeyField;
            }
            set {
                this.customerKeyField = value;
                this.RaisePropertyChanged("CustomerKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CustomerPhoneNumber {
            get {
                return this.customerPhoneNumberField;
            }
            set {
                this.customerPhoneNumberField = value;
                this.RaisePropertyChanged("CustomerPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CustomerAddress1 {
            get {
                return this.customerAddress1Field;
            }
            set {
                this.customerAddress1Field = value;
                this.RaisePropertyChanged("CustomerAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CustomerAddress2 {
            get {
                return this.customerAddress2Field;
            }
            set {
                this.customerAddress2Field = value;
                this.RaisePropertyChanged("CustomerAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CustomerCity {
            get {
                return this.customerCityField;
            }
            set {
                this.customerCityField = value;
                this.RaisePropertyChanged("CustomerCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CustomerState {
            get {
                return this.customerStateField;
            }
            set {
                this.customerStateField = value;
                this.RaisePropertyChanged("CustomerState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomerZipCode {
            get {
                return this.customerZipCodeField;
            }
            set {
                this.customerZipCodeField = value;
                this.RaisePropertyChanged("CustomerZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ARCustomerKey {
            get {
                return this.aRCustomerKeyField;
            }
            set {
                this.aRCustomerKeyField = value;
                this.RaisePropertyChanged("ARCustomerKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
                this.RaisePropertyChanged("PaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string OpenDate {
            get {
                return this.openDateField;
            }
            set {
                this.openDateField = value;
                this.RaisePropertyChanged("OpenDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
                this.RaisePropertyChanged("CloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FinalCloseDate {
            get {
                return this.finalCloseDateField;
            }
            set {
                this.finalCloseDateField = value;
                this.RaisePropertyChanged("FinalCloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
                this.RaisePropertyChanged("VIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string TotalEstimate {
            get {
                return this.totalEstimateField;
            }
            set {
                this.totalEstimateField = value;
                this.RaisePropertyChanged("TotalEstimate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ServiceContractComp {
            get {
                return this.serviceContractCompField;
            }
            set {
                this.serviceContractCompField = value;
                this.RaisePropertyChanged("ServiceContractComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ServiceContractComp2 {
            get {
                return this.serviceContractComp2Field;
            }
            set {
                this.serviceContractComp2Field = value;
                this.RaisePropertyChanged("ServiceContractComp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ServiceContractDeduct {
            get {
                return this.serviceContractDeductField;
            }
            set {
                this.serviceContractDeductField = value;
                this.RaisePropertyChanged("ServiceContractDeduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ServiceContractDeduct2 {
            get {
                return this.serviceContractDeduct2Field;
            }
            set {
                this.serviceContractDeduct2Field = value;
                this.RaisePropertyChanged("ServiceContractDeduct2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string WarrantyDeduct {
            get {
                return this.warrantyDeductField;
            }
            set {
                this.warrantyDeductField = value;
                this.RaisePropertyChanged("WarrantyDeduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string FranchiseCode {
            get {
                return this.franchiseCodeField;
            }
            set {
                this.franchiseCodeField = value;
                this.RaisePropertyChanged("FranchiseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string OdometerIn {
            get {
                return this.odometerInField;
            }
            set {
                this.odometerInField = value;
                this.RaisePropertyChanged("OdometerIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string OdometerOut {
            get {
                return this.odometerOutField;
            }
            set {
                this.odometerOutField = value;
                this.RaisePropertyChanged("OdometerOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
                this.RaisePropertyChanged("CheckNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string PurchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
                this.RaisePropertyChanged("PurchaseOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
                this.RaisePropertyChanged("ReceiptNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string PartsTotal {
            get {
                return this.partsTotalField;
            }
            set {
                this.partsTotalField = value;
                this.RaisePropertyChanged("PartsTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string LaborTotal {
            get {
                return this.laborTotalField;
            }
            set {
                this.laborTotalField = value;
                this.RaisePropertyChanged("LaborTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string SubletTotal {
            get {
                return this.subletTotalField;
            }
            set {
                this.subletTotalField = value;
                this.RaisePropertyChanged("SubletTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string ServiceContractDeductPaid {
            get {
                return this.serviceContractDeductPaidField;
            }
            set {
                this.serviceContractDeductPaidField = value;
                this.RaisePropertyChanged("ServiceContractDeductPaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string ServiceContractTotal {
            get {
                return this.serviceContractTotalField;
            }
            set {
                this.serviceContractTotalField = value;
                this.RaisePropertyChanged("ServiceContractTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string SpecialOrderDeposits {
            get {
                return this.specialOrderDepositsField;
            }
            set {
                this.specialOrderDepositsField = value;
                this.RaisePropertyChanged("SpecialOrderDeposits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string CustomerPayHazardousMaterials {
            get {
                return this.customerPayHazardousMaterialsField;
            }
            set {
                this.customerPayHazardousMaterialsField = value;
                this.RaisePropertyChanged("CustomerPayHazardousMaterials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string CustomerPaySaleTax {
            get {
                return this.customerPaySaleTaxField;
            }
            set {
                this.customerPaySaleTaxField = value;
                this.RaisePropertyChanged("CustomerPaySaleTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string WarrantySaleTax {
            get {
                return this.warrantySaleTaxField;
            }
            set {
                this.warrantySaleTaxField = value;
                this.RaisePropertyChanged("WarrantySaleTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string InternalSaleTax {
            get {
                return this.internalSaleTaxField;
            }
            set {
                this.internalSaleTaxField = value;
                this.RaisePropertyChanged("InternalSaleTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string ServiceContractSaleTax {
            get {
                return this.serviceContractSaleTaxField;
            }
            set {
                this.serviceContractSaleTaxField = value;
                this.RaisePropertyChanged("ServiceContractSaleTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string CustomerPayShopSup {
            get {
                return this.customerPayShopSupField;
            }
            set {
                this.customerPayShopSupField = value;
                this.RaisePropertyChanged("CustomerPayShopSup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string WarrantyShopSup {
            get {
                return this.warrantyShopSupField;
            }
            set {
                this.warrantyShopSupField = value;
                this.RaisePropertyChanged("WarrantyShopSup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string InternalShopSup {
            get {
                return this.internalShopSupField;
            }
            set {
                this.internalShopSupField = value;
                this.RaisePropertyChanged("InternalShopSup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string ServiceContractShopSup {
            get {
                return this.serviceContractShopSupField;
            }
            set {
                this.serviceContractShopSupField = value;
                this.RaisePropertyChanged("ServiceContractShopSup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string CouponNumber {
            get {
                return this.couponNumberField;
            }
            set {
                this.couponNumberField = value;
                this.RaisePropertyChanged("CouponNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string CouponDiscount {
            get {
                return this.couponDiscountField;
            }
            set {
                this.couponDiscountField = value;
                this.RaisePropertyChanged("CouponDiscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string TotalCouponDiscount {
            get {
                return this.totalCouponDiscountField;
            }
            set {
                this.totalCouponDiscountField = value;
                this.RaisePropertyChanged("TotalCouponDiscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string TotalSale {
            get {
                return this.totalSaleField;
            }
            set {
                this.totalSaleField = value;
                this.RaisePropertyChanged("TotalSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string TotalGross {
            get {
                return this.totalGrossField;
            }
            set {
                this.totalGrossField = value;
                this.RaisePropertyChanged("TotalGross");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string InternalAuthBy {
            get {
                return this.internalAuthByField;
            }
            set {
                this.internalAuthByField = value;
                this.RaisePropertyChanged("InternalAuthBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string TagNumber {
            get {
                return this.tagNumberField;
            }
            set {
                this.tagNumberField = value;
                this.RaisePropertyChanged("TagNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string DateTimeOfAppointment {
            get {
                return this.dateTimeOfAppointmentField;
            }
            set {
                this.dateTimeOfAppointmentField = value;
                this.RaisePropertyChanged("DateTimeOfAppointment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string DateTimeLastLineComplete {
            get {
                return this.dateTimeLastLineCompleteField;
            }
            set {
                this.dateTimeLastLineCompleteField = value;
                this.RaisePropertyChanged("DateTimeLastLineComplete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string DateTimePreInvoiced {
            get {
                return this.dateTimePreInvoicedField;
            }
            set {
                this.dateTimePreInvoicedField = value;
                this.RaisePropertyChanged("DateTimePreInvoiced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string TowedInIndicator {
            get {
                return this.towedInIndicatorField;
            }
            set {
                this.towedInIndicatorField = value;
                this.RaisePropertyChanged("TowedInIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=58)]
        public ClosedRepairOrderDetail[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class ClosedRepairOrderDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineNumberField;
        
        private ClosedRepairOrderLabor[] laborDetailsField;
        
        private ClosedRepairOrderPart[] partsField;
        
        private ClosedRepairOrderComment[] commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
                this.RaisePropertyChanged("LineNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Labor")]
        public ClosedRepairOrderLabor[] LaborDetails {
            get {
                return this.laborDetailsField;
            }
            set {
                this.laborDetailsField = value;
                this.RaisePropertyChanged("LaborDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Part")]
        public ClosedRepairOrderPart[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Comment")]
        public ClosedRepairOrderComment[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class ClosedRepairOrderLabor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineTypeField;
        
        private string lineSeqNumberField;
        
        private string transactionCodeField;
        
        private string transactionDateField;
        
        private string linePaymentMethodField;
        
        private string serviceTypeField;
        
        private string policyAdjustmentField;
        
        private string technicianIDField;
        
        private string laborOpCodeField;
        
        private string corrLaborOpCodeField;
        
        private string laborHoursField;
        
        private string laborAmountField;
        
        private string laborCostField;
        
        private string actualRetailFlagField;
        
        private string failureCodeField;
        
        private string subletVendorNumberField;
        
        private string subletInvoiceNumberField;
        
        private string couponNumberField;
        
        private string couponDiscountBasisField;
        
        private string vATCodeField;
        
        private string vATAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineType {
            get {
                return this.lineTypeField;
            }
            set {
                this.lineTypeField = value;
                this.RaisePropertyChanged("LineType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LineSeqNumber {
            get {
                return this.lineSeqNumberField;
            }
            set {
                this.lineSeqNumberField = value;
                this.RaisePropertyChanged("LineSeqNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("TransactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LinePaymentMethod {
            get {
                return this.linePaymentMethodField;
            }
            set {
                this.linePaymentMethodField = value;
                this.RaisePropertyChanged("LinePaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PolicyAdjustment {
            get {
                return this.policyAdjustmentField;
            }
            set {
                this.policyAdjustmentField = value;
                this.RaisePropertyChanged("PolicyAdjustment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TechnicianID {
            get {
                return this.technicianIDField;
            }
            set {
                this.technicianIDField = value;
                this.RaisePropertyChanged("TechnicianID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LaborOpCode {
            get {
                return this.laborOpCodeField;
            }
            set {
                this.laborOpCodeField = value;
                this.RaisePropertyChanged("LaborOpCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CorrLaborOpCode {
            get {
                return this.corrLaborOpCodeField;
            }
            set {
                this.corrLaborOpCodeField = value;
                this.RaisePropertyChanged("CorrLaborOpCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LaborHours {
            get {
                return this.laborHoursField;
            }
            set {
                this.laborHoursField = value;
                this.RaisePropertyChanged("LaborHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LaborAmount {
            get {
                return this.laborAmountField;
            }
            set {
                this.laborAmountField = value;
                this.RaisePropertyChanged("LaborAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LaborCost {
            get {
                return this.laborCostField;
            }
            set {
                this.laborCostField = value;
                this.RaisePropertyChanged("LaborCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ActualRetailFlag {
            get {
                return this.actualRetailFlagField;
            }
            set {
                this.actualRetailFlagField = value;
                this.RaisePropertyChanged("ActualRetailFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FailureCode {
            get {
                return this.failureCodeField;
            }
            set {
                this.failureCodeField = value;
                this.RaisePropertyChanged("FailureCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SubletVendorNumber {
            get {
                return this.subletVendorNumberField;
            }
            set {
                this.subletVendorNumberField = value;
                this.RaisePropertyChanged("SubletVendorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string SubletInvoiceNumber {
            get {
                return this.subletInvoiceNumberField;
            }
            set {
                this.subletInvoiceNumberField = value;
                this.RaisePropertyChanged("SubletInvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CouponNumber {
            get {
                return this.couponNumberField;
            }
            set {
                this.couponNumberField = value;
                this.RaisePropertyChanged("CouponNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CouponDiscountBasis {
            get {
                return this.couponDiscountBasisField;
            }
            set {
                this.couponDiscountBasisField = value;
                this.RaisePropertyChanged("CouponDiscountBasis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string VATCode {
            get {
                return this.vATCodeField;
            }
            set {
                this.vATCodeField = value;
                this.RaisePropertyChanged("VATCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string VATAmount {
            get {
                return this.vATAmountField;
            }
            set {
                this.vATAmountField = value;
                this.RaisePropertyChanged("VATAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class ClosedRepairOrderPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineSeqNumberField;
        
        private string transGroupField;
        
        private string transCodeField;
        
        private string specialOrderEmergencyPurchaseField;
        
        private string transDateField;
        
        private string closeDateField;
        
        private string counterPersonIDField;
        
        private string manufacturerField;
        
        private string partNumberField;
        
        private string partDescriptionField;
        
        private string stockGroupField;
        
        private string quantityField;
        
        private string costField;
        
        private string listPriceField;
        
        private string netPriceField;
        
        private string ePCostDiffField;
        
        private string specialCodeField;
        
        private string originalSpecialOrderField;
        
        private string priceOverrideField;
        
        private string groupPriceField;
        
        private string excludeFromHistoryField;
        
        private string failedPartField;
        
        private string returnToIventoryField;
        
        private string quantityOnhandAfterTransField;
        
        private string vATCodeField;
        
        private string vATAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineSeqNumber {
            get {
                return this.lineSeqNumberField;
            }
            set {
                this.lineSeqNumberField = value;
                this.RaisePropertyChanged("LineSeqNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransGroup {
            get {
                return this.transGroupField;
            }
            set {
                this.transGroupField = value;
                this.RaisePropertyChanged("TransGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransCode {
            get {
                return this.transCodeField;
            }
            set {
                this.transCodeField = value;
                this.RaisePropertyChanged("TransCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SpecialOrderEmergencyPurchase {
            get {
                return this.specialOrderEmergencyPurchaseField;
            }
            set {
                this.specialOrderEmergencyPurchaseField = value;
                this.RaisePropertyChanged("SpecialOrderEmergencyPurchase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
                this.RaisePropertyChanged("TransDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
                this.RaisePropertyChanged("CloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CounterPersonID {
            get {
                return this.counterPersonIDField;
            }
            set {
                this.counterPersonIDField = value;
                this.RaisePropertyChanged("CounterPersonID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PartDescription {
            get {
                return this.partDescriptionField;
            }
            set {
                this.partDescriptionField = value;
                this.RaisePropertyChanged("PartDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StockGroup {
            get {
                return this.stockGroupField;
            }
            set {
                this.stockGroupField = value;
                this.RaisePropertyChanged("StockGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("Cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
                this.RaisePropertyChanged("ListPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NetPrice {
            get {
                return this.netPriceField;
            }
            set {
                this.netPriceField = value;
                this.RaisePropertyChanged("NetPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string EPCostDiff {
            get {
                return this.ePCostDiffField;
            }
            set {
                this.ePCostDiffField = value;
                this.RaisePropertyChanged("EPCostDiff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string SpecialCode {
            get {
                return this.specialCodeField;
            }
            set {
                this.specialCodeField = value;
                this.RaisePropertyChanged("SpecialCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string OriginalSpecialOrder {
            get {
                return this.originalSpecialOrderField;
            }
            set {
                this.originalSpecialOrderField = value;
                this.RaisePropertyChanged("OriginalSpecialOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PriceOverride {
            get {
                return this.priceOverrideField;
            }
            set {
                this.priceOverrideField = value;
                this.RaisePropertyChanged("PriceOverride");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string GroupPrice {
            get {
                return this.groupPriceField;
            }
            set {
                this.groupPriceField = value;
                this.RaisePropertyChanged("GroupPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ExcludeFromHistory {
            get {
                return this.excludeFromHistoryField;
            }
            set {
                this.excludeFromHistoryField = value;
                this.RaisePropertyChanged("ExcludeFromHistory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string FailedPart {
            get {
                return this.failedPartField;
            }
            set {
                this.failedPartField = value;
                this.RaisePropertyChanged("FailedPart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ReturnToIventory {
            get {
                return this.returnToIventoryField;
            }
            set {
                this.returnToIventoryField = value;
                this.RaisePropertyChanged("ReturnToIventory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string QuantityOnhandAfterTrans {
            get {
                return this.quantityOnhandAfterTransField;
            }
            set {
                this.quantityOnhandAfterTransField = value;
                this.RaisePropertyChanged("QuantityOnhandAfterTrans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string VATCode {
            get {
                return this.vATCodeField;
            }
            set {
                this.vATCodeField = value;
                this.RaisePropertyChanged("VATCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string VATAmount {
            get {
                return this.vATAmountField;
            }
            set {
                this.vATAmountField = value;
                this.RaisePropertyChanged("VATAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class ClosedRepairOrderComment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineSeqNumberField;
        
        private string lineTypeField;
        
        private string transCodeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineSeqNumber {
            get {
                return this.lineSeqNumberField;
            }
            set {
                this.lineSeqNumberField = value;
                this.RaisePropertyChanged("LineSeqNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LineType {
            get {
                return this.lineTypeField;
            }
            set {
                this.lineTypeField = value;
                this.RaisePropertyChanged("LineType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransCode {
            get {
                return this.transCodeField;
            }
            set {
                this.transCodeField = value;
                this.RaisePropertyChanged("TransCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class GetClosedRepairOrderDetailRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int repairOrderNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RepairOrderNumber {
            get {
                return this.repairOrderNumberField;
            }
            set {
                this.repairOrderNumberField = value;
                this.RaisePropertyChanged("RepairOrderNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class GetClosedRepairOrdersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClosedRepairOrder[] closedRepairOrdersField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ClosedRepairOrder[] ClosedRepairOrders {
            get {
                return this.closedRepairOrdersField;
            }
            set {
                this.closedRepairOrdersField = value;
                this.RaisePropertyChanged("ClosedRepairOrders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="opentrack.dealertrack.com")]
    public partial class GetClosedRepairOrdersRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vINField;
        
        private int repairOrderNumberField;
        
        private int customerNumberField;
        
        private System.Nullable<System.DateTime> closeDateField;
        
        private System.Nullable<System.DateTime> finalCloseDateField;
        
        private System.Nullable<System.DateTime> createdDateTimeStartField;
        
        private System.Nullable<System.DateTime> createdDateTimeEndField;
        
        private System.DateTime finalCloseDateEndField;
        
        private System.Nullable<System.DateTime> finalCloseDateStartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
                this.RaisePropertyChanged("VIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RepairOrderNumber {
            get {
                return this.repairOrderNumberField;
            }
            set {
                this.repairOrderNumberField = value;
                this.RaisePropertyChanged("RepairOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
                this.RaisePropertyChanged("CloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> FinalCloseDate {
            get {
                return this.finalCloseDateField;
            }
            set {
                this.finalCloseDateField = value;
                this.RaisePropertyChanged("FinalCloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreatedDateTimeStart {
            get {
                return this.createdDateTimeStartField;
            }
            set {
                this.createdDateTimeStartField = value;
                this.RaisePropertyChanged("CreatedDateTimeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CreatedDateTimeEnd {
            get {
                return this.createdDateTimeEndField;
            }
            set {
                this.createdDateTimeEndField = value;
                this.RaisePropertyChanged("CreatedDateTimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime FinalCloseDateEnd {
            get {
                return this.finalCloseDateEndField;
            }
            set {
                this.finalCloseDateEndField = value;
                this.RaisePropertyChanged("FinalCloseDateEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> FinalCloseDateStart {
            get {
                return this.finalCloseDateStartField;
            }
            set {
                this.finalCloseDateStartField = value;
                this.RaisePropertyChanged("FinalCloseDateStart");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAPISoapChannel : OpenTrack.References.ServiceAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAPISoapClient : System.ServiceModel.ClientBase<OpenTrack.References.ServiceAPISoap>, OpenTrack.References.ServiceAPISoap {
        
        public ServiceAPISoapClient() {
        }
        
        public ServiceAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OpenTrack.References.GetClosedRepairOrdersResponse GetClosedRepairOrders(OpenTrack.References.DealerInfo dealer, OpenTrack.References.GetClosedRepairOrdersRequest request) {
            return base.Channel.GetClosedRepairOrders(dealer, request);
        }
        
        public OpenTrack.References.GetClosedRepairOrderDetailResponse GetClosedRepairOrderDetails(OpenTrack.References.DealerInfo dealer, OpenTrack.References.GetClosedRepairOrderDetailRequest request) {
            return base.Channel.GetClosedRepairOrderDetails(dealer, request);
        }
    }
}
