//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OpenTrack.Responses {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ClosedRepairOrders {
        
        private ClosedRepairOrdersClosedRepairOrder[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClosedRepairOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClosedRepairOrdersClosedRepairOrder[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ClosedRepairOrdersClosedRepairOrder {
        
        private string companyNumberField;
        
        private string repairOrderNumberField;
        
        private string repairOrderTypeField;
        
        private string warrantyRONumberField;
        
        private string serviceWriterIDField;
        
        private string rOTechnicianIDField;
        
        private string customerKeyField;
        
        private string customerNameField;
        
        private string customerAddress1Field;
        
        private string customerAddress2Field;
        
        private string customerCityField;
        
        private string customerStateField;
        
        private string customerZipCodeField;
        
        private string aRCustomerKeyField;
        
        private string paymentMethodField;
        
        private string openDateField;
        
        private string closeDateField;
        
        private string finalCloseDateField;
        
        private string vINField;
        
        private string totalEstimateField;
        
        private string serviceContractCompField;
        
        private string serviceContractComp2Field;
        
        private string serviceContractDeductField;
        
        private string serviceContractDeduct2Field;
        
        private string warrantyDeductField;
        
        private string franchiseCodeField;
        
        private string odometerInField;
        
        private string odometerOutField;
        
        private string checkNumberField;
        
        private string purchaseOrderNumberField;
        
        private string receiptNumberField;
        
        private string partsTotalField;
        
        private string laborTotalField;
        
        private string subletTotalField;
        
        private string serviceContractDeductPaidField;
        
        private string serviceContractTotalField;
        
        private string specialOrderDepositsField;
        
        private string customerPayHazardousMaterialsField;
        
        private string customerPaySaleTaxField;
        
        private string warrantySaleTaxField;
        
        private string internalSaleTaxField;
        
        private string serviceContractSaleTaxField;
        
        private string customerPayShopSupField;
        
        private string warrantyShopSupField;
        
        private string internalShopSupField;
        
        private string serviceContractShopSupField;
        
        private string couponNumberField;
        
        private string couponDiscountField;
        
        private string totalCouponDiscountField;
        
        private string totalSaleField;
        
        private string totalGrossField;
        
        private string internalAuthByField;
        
        private string tagNumberField;
        
        private string dateTimeOfAppointmentField;
        
        private string dateTimeLastLineCompleteField;
        
        private string dateTimePreInvoicedField;
        
        private string towedInIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RepairOrderNumber {
            get {
                return this.repairOrderNumberField;
            }
            set {
                this.repairOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RepairOrderType {
            get {
                return this.repairOrderTypeField;
            }
            set {
                this.repairOrderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyRONumber {
            get {
                return this.warrantyRONumberField;
            }
            set {
                this.warrantyRONumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceWriterID {
            get {
                return this.serviceWriterIDField;
            }
            set {
                this.serviceWriterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ROTechnicianID {
            get {
                return this.rOTechnicianIDField;
            }
            set {
                this.rOTechnicianIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerKey {
            get {
                return this.customerKeyField;
            }
            set {
                this.customerKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerAddress1 {
            get {
                return this.customerAddress1Field;
            }
            set {
                this.customerAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerAddress2 {
            get {
                return this.customerAddress2Field;
            }
            set {
                this.customerAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerCity {
            get {
                return this.customerCityField;
            }
            set {
                this.customerCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerState {
            get {
                return this.customerStateField;
            }
            set {
                this.customerStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerZipCode {
            get {
                return this.customerZipCodeField;
            }
            set {
                this.customerZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ARCustomerKey {
            get {
                return this.aRCustomerKeyField;
            }
            set {
                this.aRCustomerKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpenDate {
            get {
                return this.openDateField;
            }
            set {
                this.openDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FinalCloseDate {
            get {
                return this.finalCloseDateField;
            }
            set {
                this.finalCloseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalEstimate {
            get {
                return this.totalEstimateField;
            }
            set {
                this.totalEstimateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractComp {
            get {
                return this.serviceContractCompField;
            }
            set {
                this.serviceContractCompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractComp2 {
            get {
                return this.serviceContractComp2Field;
            }
            set {
                this.serviceContractComp2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractDeduct {
            get {
                return this.serviceContractDeductField;
            }
            set {
                this.serviceContractDeductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractDeduct2 {
            get {
                return this.serviceContractDeduct2Field;
            }
            set {
                this.serviceContractDeduct2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyDeduct {
            get {
                return this.warrantyDeductField;
            }
            set {
                this.warrantyDeductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FranchiseCode {
            get {
                return this.franchiseCodeField;
            }
            set {
                this.franchiseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdometerIn {
            get {
                return this.odometerInField;
            }
            set {
                this.odometerInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdometerOut {
            get {
                return this.odometerOutField;
            }
            set {
                this.odometerOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartsTotal {
            get {
                return this.partsTotalField;
            }
            set {
                this.partsTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaborTotal {
            get {
                return this.laborTotalField;
            }
            set {
                this.laborTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubletTotal {
            get {
                return this.subletTotalField;
            }
            set {
                this.subletTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractDeductPaid {
            get {
                return this.serviceContractDeductPaidField;
            }
            set {
                this.serviceContractDeductPaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractTotal {
            get {
                return this.serviceContractTotalField;
            }
            set {
                this.serviceContractTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpecialOrderDeposits {
            get {
                return this.specialOrderDepositsField;
            }
            set {
                this.specialOrderDepositsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerPayHazardousMaterials {
            get {
                return this.customerPayHazardousMaterialsField;
            }
            set {
                this.customerPayHazardousMaterialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerPaySaleTax {
            get {
                return this.customerPaySaleTaxField;
            }
            set {
                this.customerPaySaleTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantySaleTax {
            get {
                return this.warrantySaleTaxField;
            }
            set {
                this.warrantySaleTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalSaleTax {
            get {
                return this.internalSaleTaxField;
            }
            set {
                this.internalSaleTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractSaleTax {
            get {
                return this.serviceContractSaleTaxField;
            }
            set {
                this.serviceContractSaleTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerPayShopSup {
            get {
                return this.customerPayShopSupField;
            }
            set {
                this.customerPayShopSupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyShopSup {
            get {
                return this.warrantyShopSupField;
            }
            set {
                this.warrantyShopSupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalShopSup {
            get {
                return this.internalShopSupField;
            }
            set {
                this.internalShopSupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContractShopSup {
            get {
                return this.serviceContractShopSupField;
            }
            set {
                this.serviceContractShopSupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CouponNumber {
            get {
                return this.couponNumberField;
            }
            set {
                this.couponNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CouponDiscount {
            get {
                return this.couponDiscountField;
            }
            set {
                this.couponDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalCouponDiscount {
            get {
                return this.totalCouponDiscountField;
            }
            set {
                this.totalCouponDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalSale {
            get {
                return this.totalSaleField;
            }
            set {
                this.totalSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalGross {
            get {
                return this.totalGrossField;
            }
            set {
                this.totalGrossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalAuthBy {
            get {
                return this.internalAuthByField;
            }
            set {
                this.internalAuthByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TagNumber {
            get {
                return this.tagNumberField;
            }
            set {
                this.tagNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateTimeOfAppointment {
            get {
                return this.dateTimeOfAppointmentField;
            }
            set {
                this.dateTimeOfAppointmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateTimeLastLineComplete {
            get {
                return this.dateTimeLastLineCompleteField;
            }
            set {
                this.dateTimeLastLineCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateTimePreInvoiced {
            get {
                return this.dateTimePreInvoicedField;
            }
            set {
                this.dateTimePreInvoicedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TowedInIndicator {
            get {
                return this.towedInIndicatorField;
            }
            set {
                this.towedInIndicatorField = value;
            }
        }
    }
}
