//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GetClosedRepairOrderDetailResponse {
    
    private GetClosedRepairOrderDetailResponseRepairOrders[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RepairOrders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GetClosedRepairOrderDetailResponseRepairOrders[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetClosedRepairOrderDetailResponseRepairOrders {
    
    private GetClosedRepairOrderDetailResponseRepairOrdersRepairOrder[] repairOrderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RepairOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GetClosedRepairOrderDetailResponseRepairOrdersRepairOrder[] RepairOrder {
        get {
            return this.repairOrderField;
        }
        set {
            this.repairOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetClosedRepairOrderDetailResponseRepairOrdersRepairOrder {
    
    private string companyNumberField;
    
    private string repairOrderNumberField;
    
    private string repairOrderTypeField;
    
    private string warrantyRONumberField;
    
    private string serviceWriterIDField;
    
    private string rOTechnicianIDField;
    
    private string customerKeyField;
    
    private string customerNameField;
    
    private string customerAddress1Field;
    
    private string customerAddress2Field;
    
    private string customerCityField;
    
    private string customerStateField;
    
    private string customerZipCodeField;
    
    private string aRCustomerKeyField;
    
    private string paymentMethodField;
    
    private string openDateField;
    
    private string closeDateField;
    
    private string finalCloseDateField;
    
    private string vINField;
    
    private string totalEstimateField;
    
    private string serviceContractCompField;
    
    private string serviceContractComp2Field;
    
    private string serviceContractDeductField;
    
    private string serviceContractDeduct2Field;
    
    private string warrantyDeductField;
    
    private string franchiseCodeField;
    
    private string odometerInField;
    
    private string odometerOutField;
    
    private string checkNumberField;
    
    private string purchaseOrderNumberField;
    
    private string receiptNumberField;
    
    private string partsTotalField;
    
    private string laborTotalField;
    
    private string subletTotalField;
    
    private string serviceContractDeductPaidField;
    
    private string serviceContractTotalField;
    
    private string specialOrderDepositsField;
    
    private string customerPayHazardousMaterialsField;
    
    private string customerPaySaleTaxField;
    
    private string warrantySaleTaxField;
    
    private string internalSaleTaxField;
    
    private string serviceContractSaleTaxField;
    
    private string customerPayShopSupField;
    
    private string warrantyShopSupField;
    
    private string internalShopSupField;
    
    private string serviceContractShopSupField;
    
    private string couponNumberField;
    
    private string couponDiscountField;
    
    private string totalCouponDiscountField;
    
    private string totalSaleField;
    
    private string totalGrossField;
    
    private string internalAuthByField;
    
    private string tagNumberField;
    
    private string dateTimeOfAppointmentField;
    
    private string dateTimeLastLineCompleteField;
    
    private string dateTimePreInvoicedField;
    
    private string towedInIndicatorField;
    
    private GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetail[] detailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompanyNumber {
        get {
            return this.companyNumberField;
        }
        set {
            this.companyNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RepairOrderNumber {
        get {
            return this.repairOrderNumberField;
        }
        set {
            this.repairOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RepairOrderType {
        get {
            return this.repairOrderTypeField;
        }
        set {
            this.repairOrderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyRONumber {
        get {
            return this.warrantyRONumberField;
        }
        set {
            this.warrantyRONumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceWriterID {
        get {
            return this.serviceWriterIDField;
        }
        set {
            this.serviceWriterIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ROTechnicianID {
        get {
            return this.rOTechnicianIDField;
        }
        set {
            this.rOTechnicianIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerKey {
        get {
            return this.customerKeyField;
        }
        set {
            this.customerKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerAddress1 {
        get {
            return this.customerAddress1Field;
        }
        set {
            this.customerAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerAddress2 {
        get {
            return this.customerAddress2Field;
        }
        set {
            this.customerAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerCity {
        get {
            return this.customerCityField;
        }
        set {
            this.customerCityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerState {
        get {
            return this.customerStateField;
        }
        set {
            this.customerStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerZipCode {
        get {
            return this.customerZipCodeField;
        }
        set {
            this.customerZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ARCustomerKey {
        get {
            return this.aRCustomerKeyField;
        }
        set {
            this.aRCustomerKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaymentMethod {
        get {
            return this.paymentMethodField;
        }
        set {
            this.paymentMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OpenDate {
        get {
            return this.openDateField;
        }
        set {
            this.openDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CloseDate {
        get {
            return this.closeDateField;
        }
        set {
            this.closeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FinalCloseDate {
        get {
            return this.finalCloseDateField;
        }
        set {
            this.finalCloseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VIN {
        get {
            return this.vINField;
        }
        set {
            this.vINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalEstimate {
        get {
            return this.totalEstimateField;
        }
        set {
            this.totalEstimateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractComp {
        get {
            return this.serviceContractCompField;
        }
        set {
            this.serviceContractCompField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractComp2 {
        get {
            return this.serviceContractComp2Field;
        }
        set {
            this.serviceContractComp2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractDeduct {
        get {
            return this.serviceContractDeductField;
        }
        set {
            this.serviceContractDeductField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractDeduct2 {
        get {
            return this.serviceContractDeduct2Field;
        }
        set {
            this.serviceContractDeduct2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyDeduct {
        get {
            return this.warrantyDeductField;
        }
        set {
            this.warrantyDeductField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FranchiseCode {
        get {
            return this.franchiseCodeField;
        }
        set {
            this.franchiseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OdometerIn {
        get {
            return this.odometerInField;
        }
        set {
            this.odometerInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OdometerOut {
        get {
            return this.odometerOutField;
        }
        set {
            this.odometerOutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CheckNumber {
        get {
            return this.checkNumberField;
        }
        set {
            this.checkNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PurchaseOrderNumber {
        get {
            return this.purchaseOrderNumberField;
        }
        set {
            this.purchaseOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReceiptNumber {
        get {
            return this.receiptNumberField;
        }
        set {
            this.receiptNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartsTotal {
        get {
            return this.partsTotalField;
        }
        set {
            this.partsTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborTotal {
        get {
            return this.laborTotalField;
        }
        set {
            this.laborTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubletTotal {
        get {
            return this.subletTotalField;
        }
        set {
            this.subletTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractDeductPaid {
        get {
            return this.serviceContractDeductPaidField;
        }
        set {
            this.serviceContractDeductPaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractTotal {
        get {
            return this.serviceContractTotalField;
        }
        set {
            this.serviceContractTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderDeposits {
        get {
            return this.specialOrderDepositsField;
        }
        set {
            this.specialOrderDepositsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayHazardousMaterials {
        get {
            return this.customerPayHazardousMaterialsField;
        }
        set {
            this.customerPayHazardousMaterialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPaySaleTax {
        get {
            return this.customerPaySaleTaxField;
        }
        set {
            this.customerPaySaleTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantySaleTax {
        get {
            return this.warrantySaleTaxField;
        }
        set {
            this.warrantySaleTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalSaleTax {
        get {
            return this.internalSaleTaxField;
        }
        set {
            this.internalSaleTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractSaleTax {
        get {
            return this.serviceContractSaleTaxField;
        }
        set {
            this.serviceContractSaleTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPayShopSup {
        get {
            return this.customerPayShopSupField;
        }
        set {
            this.customerPayShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WarrantyShopSup {
        get {
            return this.warrantyShopSupField;
        }
        set {
            this.warrantyShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalShopSup {
        get {
            return this.internalShopSupField;
        }
        set {
            this.internalShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceContractShopSup {
        get {
            return this.serviceContractShopSupField;
        }
        set {
            this.serviceContractShopSupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponNumber {
        get {
            return this.couponNumberField;
        }
        set {
            this.couponNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponDiscount {
        get {
            return this.couponDiscountField;
        }
        set {
            this.couponDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalCouponDiscount {
        get {
            return this.totalCouponDiscountField;
        }
        set {
            this.totalCouponDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalSale {
        get {
            return this.totalSaleField;
        }
        set {
            this.totalSaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalGross {
        get {
            return this.totalGrossField;
        }
        set {
            this.totalGrossField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalAuthBy {
        get {
            return this.internalAuthByField;
        }
        set {
            this.internalAuthByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TagNumber {
        get {
            return this.tagNumberField;
        }
        set {
            this.tagNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateTimeOfAppointment {
        get {
            return this.dateTimeOfAppointmentField;
        }
        set {
            this.dateTimeOfAppointmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateTimeLastLineComplete {
        get {
            return this.dateTimeLastLineCompleteField;
        }
        set {
            this.dateTimeLastLineCompleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateTimePreInvoiced {
        get {
            return this.dateTimePreInvoicedField;
        }
        set {
            this.dateTimePreInvoicedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TowedInIndicator {
        get {
            return this.towedInIndicatorField;
        }
        set {
            this.towedInIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ClosedRepairOrderDetail", typeof(GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetail), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetail[] Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetail {
    
    private string lineNumberField;
    
    private GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailLaborDetailsLabor[] laborDetailsField;
    
    private GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailPartsPart[] partsField;
    
    private GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailCommentsComment[] commentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Labor", typeof(GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailLaborDetailsLabor), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailLaborDetailsLabor[] LaborDetails {
        get {
            return this.laborDetailsField;
        }
        set {
            this.laborDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Part", typeof(GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailPartsPart), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailPartsPart[] Parts {
        get {
            return this.partsField;
        }
        set {
            this.partsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Comment", typeof(GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailCommentsComment), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailCommentsComment[] Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailLaborDetailsLabor {
    
    private string lineTypeField;
    
    private string lineSeqNumberField;
    
    private string transactionCodeField;
    
    private string transactionDateField;
    
    private string linePaymentMethodField;
    
    private string serviceTypeField;
    
    private string policyAdjustmentField;
    
    private string technicianIDField;
    
    private string laborOpCodeField;
    
    private string corrLaborOpCodeField;
    
    private string laborHoursField;
    
    private string laborAmountField;
    
    private string laborCostField;
    
    private string actualRetailFlagField;
    
    private string failureCodeField;
    
    private string subletVendorNumberField;
    
    private string subletInvoiceNumberField;
    
    private string couponNumberField;
    
    private string couponDiscountBasisField;
    
    private string vATCodeField;
    
    private string vATAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineType {
        get {
            return this.lineTypeField;
        }
        set {
            this.lineTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineSeqNumber {
        get {
            return this.lineSeqNumberField;
        }
        set {
            this.lineSeqNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionCode {
        get {
            return this.transactionCodeField;
        }
        set {
            this.transactionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionDate {
        get {
            return this.transactionDateField;
        }
        set {
            this.transactionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LinePaymentMethod {
        get {
            return this.linePaymentMethodField;
        }
        set {
            this.linePaymentMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PolicyAdjustment {
        get {
            return this.policyAdjustmentField;
        }
        set {
            this.policyAdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TechnicianID {
        get {
            return this.technicianIDField;
        }
        set {
            this.technicianIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborOpCode {
        get {
            return this.laborOpCodeField;
        }
        set {
            this.laborOpCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CorrLaborOpCode {
        get {
            return this.corrLaborOpCodeField;
        }
        set {
            this.corrLaborOpCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborHours {
        get {
            return this.laborHoursField;
        }
        set {
            this.laborHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborAmount {
        get {
            return this.laborAmountField;
        }
        set {
            this.laborAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LaborCost {
        get {
            return this.laborCostField;
        }
        set {
            this.laborCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActualRetailFlag {
        get {
            return this.actualRetailFlagField;
        }
        set {
            this.actualRetailFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailureCode {
        get {
            return this.failureCodeField;
        }
        set {
            this.failureCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubletVendorNumber {
        get {
            return this.subletVendorNumberField;
        }
        set {
            this.subletVendorNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubletInvoiceNumber {
        get {
            return this.subletInvoiceNumberField;
        }
        set {
            this.subletInvoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponNumber {
        get {
            return this.couponNumberField;
        }
        set {
            this.couponNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CouponDiscountBasis {
        get {
            return this.couponDiscountBasisField;
        }
        set {
            this.couponDiscountBasisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATCode {
        get {
            return this.vATCodeField;
        }
        set {
            this.vATCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATAmount {
        get {
            return this.vATAmountField;
        }
        set {
            this.vATAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailPartsPart {
    
    private string lineSeqNumberField;
    
    private string transGroupField;
    
    private string transCodeField;
    
    private string specialOrderEmergencyPurchaseField;
    
    private string transDateField;
    
    private string closeDateField;
    
    private string counterPersonIDField;
    
    private string manufacturerField;
    
    private string partNumberField;
    
    private string partDescriptionField;
    
    private string stockGroupField;
    
    private string quantityField;
    
    private string costField;
    
    private string listPriceField;
    
    private string netPriceField;
    
    private string ePCostDiffField;
    
    private string specialCodeField;
    
    private string originalSpecialOrderField;
    
    private string priceOverrideField;
    
    private string groupPriceField;
    
    private string excludeFromHistoryField;
    
    private string failedPartField;
    
    private string returnToIventoryField;
    
    private string quantityOnhandAfterTransField;
    
    private string vATCodeField;
    
    private string vATAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineSeqNumber {
        get {
            return this.lineSeqNumberField;
        }
        set {
            this.lineSeqNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransGroup {
        get {
            return this.transGroupField;
        }
        set {
            this.transGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransCode {
        get {
            return this.transCodeField;
        }
        set {
            this.transCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialOrderEmergencyPurchase {
        get {
            return this.specialOrderEmergencyPurchaseField;
        }
        set {
            this.specialOrderEmergencyPurchaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransDate {
        get {
            return this.transDateField;
        }
        set {
            this.transDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CloseDate {
        get {
            return this.closeDateField;
        }
        set {
            this.closeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CounterPersonID {
        get {
            return this.counterPersonIDField;
        }
        set {
            this.counterPersonIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartNumber {
        get {
            return this.partNumberField;
        }
        set {
            this.partNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PartDescription {
        get {
            return this.partDescriptionField;
        }
        set {
            this.partDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StockGroup {
        get {
            return this.stockGroupField;
        }
        set {
            this.stockGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ListPrice {
        get {
            return this.listPriceField;
        }
        set {
            this.listPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetPrice {
        get {
            return this.netPriceField;
        }
        set {
            this.netPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EPCostDiff {
        get {
            return this.ePCostDiffField;
        }
        set {
            this.ePCostDiffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialCode {
        get {
            return this.specialCodeField;
        }
        set {
            this.specialCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OriginalSpecialOrder {
        get {
            return this.originalSpecialOrderField;
        }
        set {
            this.originalSpecialOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PriceOverride {
        get {
            return this.priceOverrideField;
        }
        set {
            this.priceOverrideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GroupPrice {
        get {
            return this.groupPriceField;
        }
        set {
            this.groupPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExcludeFromHistory {
        get {
            return this.excludeFromHistoryField;
        }
        set {
            this.excludeFromHistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailedPart {
        get {
            return this.failedPartField;
        }
        set {
            this.failedPartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReturnToIventory {
        get {
            return this.returnToIventoryField;
        }
        set {
            this.returnToIventoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string QuantityOnhandAfterTrans {
        get {
            return this.quantityOnhandAfterTransField;
        }
        set {
            this.quantityOnhandAfterTransField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATCode {
        get {
            return this.vATCodeField;
        }
        set {
            this.vATCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATAmount {
        get {
            return this.vATAmountField;
        }
        set {
            this.vATAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetClosedRepairOrderDetailResponseRepairOrdersRepairOrderDetailsClosedRepairOrderDetailCommentsComment {
    
    private string lineSeqNumberField;
    
    private string lineTypeField;
    
    private string transCodeField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineSeqNumber {
        get {
            return this.lineSeqNumberField;
        }
        set {
            this.lineSeqNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineType {
        get {
            return this.lineTypeField;
        }
        set {
            this.lineTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransCode {
        get {
            return this.transCodeField;
        }
        set {
            this.transCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}
