//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OpenTrack.Responses {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PartsInventoryResponse {
        
        private PartsInventoryResponsePart[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Part", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartsInventoryResponsePart[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PartsInventoryResponsePart {
        
        private string companyNumberField;
        
        private string manufacturerField;
        
        private string partNumberField;
        
        private string partDescriptionField;
        
        private string stockingGroupField;
        
        private string statusField;
        
        private string obsoleteField;
        
        private string returnCodeField;
        
        private string arrivalCodeField;
        
        private string stockPromoCodeField;
        
        private string specialOrderCodeField;
        
        private string priceUpdateField;
        
        private string kitPartField;
        
        private string componentPartField;
        
        private string associateWithPartField;
        
        private string alternatePartField;
        
        private string corePartField;
        
        private string merchCodeField;
        
        private string priceSymbolField;
        
        private string prodCodeClassField;
        
        private string fleetAllowanceField;
        
        private string groupCodeField;
        
        private string binLocationField;
        
        private string shelfLocationField;
        
        private string quantityOnHandField;
        
        private string quantityReservedField;
        
        private string quantityOnOrderField;
        
        private string quantityOnBackOrderField;
        
        private string quantityOnSpecialOrderField;
        
        private string placeOnOrderField;
        
        private string placeOnSpecialOrderField;
        
        private string packQuantityField;
        
        private string minSalesQuantityField;
        
        private string costField;
        
        private string listPriceField;
        
        private string tradePriceField;
        
        private string wholesaleCompField;
        
        private string wholesaleCompFleetField;
        
        private string flatPriceField;
        
        private string minMaxPackAdjField;
        
        private string dynamDaysSupplyField;
        
        private string minimumOnHandField;
        
        private string maximumOnHandField;
        
        private string lowModelYearField;
        
        private string highModelYearField;
        
        private string dateInInventoryField;
        
        private string datePhasedOutField;
        
        private string dateLastSoldField;
        
        private string inventoryTurnsField;
        
        private string bestStockLevelField;
        
        private string stockStatusField;
        
        private string recentDemandField;
        
        private string priorDemandField;
        
        private string recentWorkDaysField;
        
        private string priorWorkDaysField;
        
        private string weightedDailyAverageField;
        
        private string salesDemandField;
        
        private string lostSalesDemandField;
        
        private string specOrderDemandField;
        
        private string nonStockDemandField;
        
        private string returnDemandField;
        
        private string inventoryValueField;
        
        private string totalQuantitySoldField;
        
        private string totalCostSalesField;
        
        private string stockPurchasesField;
        
        private string displayPartNumberField;
        
        private string sortPartNumberField;
        
        private string oldPartNumberField;
        
        private string newPartNumberField;
        
        private string corePartNumberField;
        
        private string remarksField;
        
        private string displayRemarksField;
        
        private string bulkItemActualWeightField;
        
        private string secondaryBinLocationField;
        
        private string classCodeField;
        
        private string partDealerToDealerPriceField;
        
        private string partSubsidiaryPriceField;
        
        private string partDealerToDealerCodeField;
        
        private string emergencyRepairPackageField;
        
        private string partLsgCodeField;
        
        private string brandCodeField;
        
        private string partcommondcodeField;
        
        private string partCrossShipCodeField;
        
        private string partDiscountCodeField;
        
        private string partDirectshipCodeField;
        
        private string partHazardCodeField;
        
        private string partInterchangeSubstituteField;
        
        private string partLargeQuantityCodeField;
        
        private string partMaximumOrderQuantityField;
        
        private string partMinimumOrderQuantityField;
        
        private string partObsoleteStatusField;
        
        private string programPartAllowanceCodeField;
        
        private string partPricingDiscountPerField;
        
        private string programPartReturnableCodeField;
        
        private string partSizeCodeField;
        
        private string partTypeField;
        
        private string partVolumeDiscountFlagField;
        
        private string secondaryShelfField;
        
        private string weightCodeField;
        
        private string unitOfMeasureField;
        
        private string stockCodeField;
        
        private string quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartDescription {
            get {
                return this.partDescriptionField;
            }
            set {
                this.partDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockingGroup {
            get {
                return this.stockingGroupField;
            }
            set {
                this.stockingGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Obsolete {
            get {
                return this.obsoleteField;
            }
            set {
                this.obsoleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArrivalCode {
            get {
                return this.arrivalCodeField;
            }
            set {
                this.arrivalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockPromoCode {
            get {
                return this.stockPromoCodeField;
            }
            set {
                this.stockPromoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpecialOrderCode {
            get {
                return this.specialOrderCodeField;
            }
            set {
                this.specialOrderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceUpdate {
            get {
                return this.priceUpdateField;
            }
            set {
                this.priceUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KitPart {
            get {
                return this.kitPartField;
            }
            set {
                this.kitPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ComponentPart {
            get {
                return this.componentPartField;
            }
            set {
                this.componentPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssociateWithPart {
            get {
                return this.associateWithPartField;
            }
            set {
                this.associateWithPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlternatePart {
            get {
                return this.alternatePartField;
            }
            set {
                this.alternatePartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CorePart {
            get {
                return this.corePartField;
            }
            set {
                this.corePartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MerchCode {
            get {
                return this.merchCodeField;
            }
            set {
                this.merchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceSymbol {
            get {
                return this.priceSymbolField;
            }
            set {
                this.priceSymbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProdCodeClass {
            get {
                return this.prodCodeClassField;
            }
            set {
                this.prodCodeClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FleetAllowance {
            get {
                return this.fleetAllowanceField;
            }
            set {
                this.fleetAllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GroupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinLocation {
            get {
                return this.binLocationField;
            }
            set {
                this.binLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShelfLocation {
            get {
                return this.shelfLocationField;
            }
            set {
                this.shelfLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityOnHand {
            get {
                return this.quantityOnHandField;
            }
            set {
                this.quantityOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityReserved {
            get {
                return this.quantityReservedField;
            }
            set {
                this.quantityReservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityOnOrder {
            get {
                return this.quantityOnOrderField;
            }
            set {
                this.quantityOnOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityOnBackOrder {
            get {
                return this.quantityOnBackOrderField;
            }
            set {
                this.quantityOnBackOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityOnSpecialOrder {
            get {
                return this.quantityOnSpecialOrderField;
            }
            set {
                this.quantityOnSpecialOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlaceOnOrder {
            get {
                return this.placeOnOrderField;
            }
            set {
                this.placeOnOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlaceOnSpecialOrder {
            get {
                return this.placeOnSpecialOrderField;
            }
            set {
                this.placeOnSpecialOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackQuantity {
            get {
                return this.packQuantityField;
            }
            set {
                this.packQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinSalesQuantity {
            get {
                return this.minSalesQuantityField;
            }
            set {
                this.minSalesQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TradePrice {
            get {
                return this.tradePriceField;
            }
            set {
                this.tradePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WholesaleComp {
            get {
                return this.wholesaleCompField;
            }
            set {
                this.wholesaleCompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WholesaleCompFleet {
            get {
                return this.wholesaleCompFleetField;
            }
            set {
                this.wholesaleCompFleetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlatPrice {
            get {
                return this.flatPriceField;
            }
            set {
                this.flatPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinMaxPackAdj {
            get {
                return this.minMaxPackAdjField;
            }
            set {
                this.minMaxPackAdjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DynamDaysSupply {
            get {
                return this.dynamDaysSupplyField;
            }
            set {
                this.dynamDaysSupplyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimumOnHand {
            get {
                return this.minimumOnHandField;
            }
            set {
                this.minimumOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaximumOnHand {
            get {
                return this.maximumOnHandField;
            }
            set {
                this.maximumOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LowModelYear {
            get {
                return this.lowModelYearField;
            }
            set {
                this.lowModelYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HighModelYear {
            get {
                return this.highModelYearField;
            }
            set {
                this.highModelYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateInInventory {
            get {
                return this.dateInInventoryField;
            }
            set {
                this.dateInInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DatePhasedOut {
            get {
                return this.datePhasedOutField;
            }
            set {
                this.datePhasedOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateLastSold {
            get {
                return this.dateLastSoldField;
            }
            set {
                this.dateLastSoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryTurns {
            get {
                return this.inventoryTurnsField;
            }
            set {
                this.inventoryTurnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BestStockLevel {
            get {
                return this.bestStockLevelField;
            }
            set {
                this.bestStockLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockStatus {
            get {
                return this.stockStatusField;
            }
            set {
                this.stockStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RecentDemand {
            get {
                return this.recentDemandField;
            }
            set {
                this.recentDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriorDemand {
            get {
                return this.priorDemandField;
            }
            set {
                this.priorDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RecentWorkDays {
            get {
                return this.recentWorkDaysField;
            }
            set {
                this.recentWorkDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriorWorkDays {
            get {
                return this.priorWorkDaysField;
            }
            set {
                this.priorWorkDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WeightedDailyAverage {
            get {
                return this.weightedDailyAverageField;
            }
            set {
                this.weightedDailyAverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesDemand {
            get {
                return this.salesDemandField;
            }
            set {
                this.salesDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LostSalesDemand {
            get {
                return this.lostSalesDemandField;
            }
            set {
                this.lostSalesDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpecOrderDemand {
            get {
                return this.specOrderDemandField;
            }
            set {
                this.specOrderDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NonStockDemand {
            get {
                return this.nonStockDemandField;
            }
            set {
                this.nonStockDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnDemand {
            get {
                return this.returnDemandField;
            }
            set {
                this.returnDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryValue {
            get {
                return this.inventoryValueField;
            }
            set {
                this.inventoryValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalQuantitySold {
            get {
                return this.totalQuantitySoldField;
            }
            set {
                this.totalQuantitySoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalCostSales {
            get {
                return this.totalCostSalesField;
            }
            set {
                this.totalCostSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockPurchases {
            get {
                return this.stockPurchasesField;
            }
            set {
                this.stockPurchasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayPartNumber {
            get {
                return this.displayPartNumberField;
            }
            set {
                this.displayPartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SortPartNumber {
            get {
                return this.sortPartNumberField;
            }
            set {
                this.sortPartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OldPartNumber {
            get {
                return this.oldPartNumberField;
            }
            set {
                this.oldPartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewPartNumber {
            get {
                return this.newPartNumberField;
            }
            set {
                this.newPartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CorePartNumber {
            get {
                return this.corePartNumberField;
            }
            set {
                this.corePartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayRemarks {
            get {
                return this.displayRemarksField;
            }
            set {
                this.displayRemarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BulkItemActualWeight {
            get {
                return this.bulkItemActualWeightField;
            }
            set {
                this.bulkItemActualWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SecondaryBinLocation {
            get {
                return this.secondaryBinLocationField;
            }
            set {
                this.secondaryBinLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartDealerToDealerPrice {
            get {
                return this.partDealerToDealerPriceField;
            }
            set {
                this.partDealerToDealerPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartSubsidiaryPrice {
            get {
                return this.partSubsidiaryPriceField;
            }
            set {
                this.partSubsidiaryPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartDealerToDealerCode {
            get {
                return this.partDealerToDealerCodeField;
            }
            set {
                this.partDealerToDealerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmergencyRepairPackage {
            get {
                return this.emergencyRepairPackageField;
            }
            set {
                this.emergencyRepairPackageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartLsgCode {
            get {
                return this.partLsgCodeField;
            }
            set {
                this.partLsgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BrandCode {
            get {
                return this.brandCodeField;
            }
            set {
                this.brandCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Partcommondcode {
            get {
                return this.partcommondcodeField;
            }
            set {
                this.partcommondcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartCrossShipCode {
            get {
                return this.partCrossShipCodeField;
            }
            set {
                this.partCrossShipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartDiscountCode {
            get {
                return this.partDiscountCodeField;
            }
            set {
                this.partDiscountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartDirectshipCode {
            get {
                return this.partDirectshipCodeField;
            }
            set {
                this.partDirectshipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartHazardCode {
            get {
                return this.partHazardCodeField;
            }
            set {
                this.partHazardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartInterchangeSubstitute {
            get {
                return this.partInterchangeSubstituteField;
            }
            set {
                this.partInterchangeSubstituteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartLargeQuantityCode {
            get {
                return this.partLargeQuantityCodeField;
            }
            set {
                this.partLargeQuantityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartMaximumOrderQuantity {
            get {
                return this.partMaximumOrderQuantityField;
            }
            set {
                this.partMaximumOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartMinimumOrderQuantity {
            get {
                return this.partMinimumOrderQuantityField;
            }
            set {
                this.partMinimumOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartObsoleteStatus {
            get {
                return this.partObsoleteStatusField;
            }
            set {
                this.partObsoleteStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProgramPartAllowanceCode {
            get {
                return this.programPartAllowanceCodeField;
            }
            set {
                this.programPartAllowanceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartPricingDiscountPer {
            get {
                return this.partPricingDiscountPerField;
            }
            set {
                this.partPricingDiscountPerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProgramPartReturnableCode {
            get {
                return this.programPartReturnableCodeField;
            }
            set {
                this.programPartReturnableCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartSizeCode {
            get {
                return this.partSizeCodeField;
            }
            set {
                this.partSizeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartType {
            get {
                return this.partTypeField;
            }
            set {
                this.partTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartVolumeDiscountFlag {
            get {
                return this.partVolumeDiscountFlagField;
            }
            set {
                this.partVolumeDiscountFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SecondaryShelf {
            get {
                return this.secondaryShelfField;
            }
            set {
                this.secondaryShelfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WeightCode {
            get {
                return this.weightCodeField;
            }
            set {
                this.weightCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
}
