//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OpenTrack.Responses {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ServiceTechsTable {
        
        private ServiceTechsTableServiceTechRecord[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceTechRecord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTechsTableServiceTechRecord[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ServiceTechsTableServiceTechRecord {
        
        private string companyNumberField;
        
        private string technicianIdField;
        
        private string nameField;
        
        private string employeeNumberField;
        
        private string payrollEmployeeNumberField;
        
        private string stateCertificationNumberField;
        
        private string activeField;
        
        private string assignedServiceWriterField;
        
        private string defaultServiceTypeField;
        
        private string laborRateAField;
        
        private string laborRateBField;
        
        private string laborRateCField;
        
        private string laborRateDField;
        
        private string internalLaborRateAField;
        
        private string internalLaborRateBField;
        
        private string internalLaborRateCField;
        
        private string internalLaborRateDField;
        
        private string serviceLaborRateAField;
        
        private string serviceLaborRateBField;
        
        private string serviceLaborRateCField;
        
        private string serviceLaborRateDField;
        
        private string warrantyLaborRateAField;
        
        private string warrantyLaborRateBField;
        
        private string warrantyLaborRateCField;
        
        private string warrantyLaborRateDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TechnicianId {
            get {
                return this.technicianIdField;
            }
            set {
                this.technicianIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmployeeNumber {
            get {
                return this.employeeNumberField;
            }
            set {
                this.employeeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PayrollEmployeeNumber {
            get {
                return this.payrollEmployeeNumberField;
            }
            set {
                this.payrollEmployeeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateCertificationNumber {
            get {
                return this.stateCertificationNumberField;
            }
            set {
                this.stateCertificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssignedServiceWriter {
            get {
                return this.assignedServiceWriterField;
            }
            set {
                this.assignedServiceWriterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefaultServiceType {
            get {
                return this.defaultServiceTypeField;
            }
            set {
                this.defaultServiceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaborRateA {
            get {
                return this.laborRateAField;
            }
            set {
                this.laborRateAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaborRateB {
            get {
                return this.laborRateBField;
            }
            set {
                this.laborRateBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaborRateC {
            get {
                return this.laborRateCField;
            }
            set {
                this.laborRateCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaborRateD {
            get {
                return this.laborRateDField;
            }
            set {
                this.laborRateDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalLaborRateA {
            get {
                return this.internalLaborRateAField;
            }
            set {
                this.internalLaborRateAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalLaborRateB {
            get {
                return this.internalLaborRateBField;
            }
            set {
                this.internalLaborRateBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalLaborRateC {
            get {
                return this.internalLaborRateCField;
            }
            set {
                this.internalLaborRateCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalLaborRateD {
            get {
                return this.internalLaborRateDField;
            }
            set {
                this.internalLaborRateDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceLaborRateA {
            get {
                return this.serviceLaborRateAField;
            }
            set {
                this.serviceLaborRateAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceLaborRateB {
            get {
                return this.serviceLaborRateBField;
            }
            set {
                this.serviceLaborRateBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceLaborRateC {
            get {
                return this.serviceLaborRateCField;
            }
            set {
                this.serviceLaborRateCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceLaborRateD {
            get {
                return this.serviceLaborRateDField;
            }
            set {
                this.serviceLaborRateDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyLaborRateA {
            get {
                return this.warrantyLaborRateAField;
            }
            set {
                this.warrantyLaborRateAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyLaborRateB {
            get {
                return this.warrantyLaborRateBField;
            }
            set {
                this.warrantyLaborRateBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyLaborRateC {
            get {
                return this.warrantyLaborRateCField;
            }
            set {
                this.warrantyLaborRateCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyLaborRateD {
            get {
                return this.warrantyLaborRateDField;
            }
            set {
                this.warrantyLaborRateDField = value;
            }
        }
    }
}
