//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OpenTrack.Responses {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VehicleLookupResponse {
        
        private VehicleLookupResponseVehicle[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vehicle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VehicleLookupResponseVehicle[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VehicleLookupResponseVehicle {
        
        private string companyNumberField;
        
        private string vINField;
        
        private string stockNumberField;
        
        private string documentNumberField;
        
        private string statusField;
        
        private string gLAppliedField;
        
        private string typeNUField;
        
        private string businessOfficeFranchiseCodeField;
        
        private string serviceFranchiseCodeField;
        
        private string manufacturerCodeField;
        
        private string vehicleCodeField;
        
        private string modelYearField;
        
        private string makeField;
        
        private string modelCodeField;
        
        private string modelField;
        
        private string bodyStyleField;
        
        private string colorField;
        
        private string trimField;
        
        private string fuelTypeField;
        
        private string mPGField;
        
        private string cylindersField;
        
        private string truckField;
        
        private string fourWheelDriveField;
        
        private string turboField;
        
        private string colorCodeField;
        
        private string engineCodeField;
        
        private string transmissionCodeField;
        
        private string ignitionKeyCodeField;
        
        private string trunkKeyCodeField;
        
        private string keylessCodeField;
        
        private string radioCodeField;
        
        private string wheelLockCodeField;
        
        private string dealerCodeField;
        
        private string locationField;
        
        private string odometerField;
        
        private string dateInInventoryField;
        
        private string dateInServiceField;
        
        private string dateDeliveredField;
        
        private string dateOrderedField;
        
        private string saleAccountField;
        
        private string inventoryAccountField;
        
        private string demoNameField;
        
        private string warrantyMonthsField;
        
        private string warrantyMilesField;
        
        private string warrantyDeductField;
        
        private string listPriceField;
        
        private string vehicleCostField;
        
        private string optionPackageField;
        
        private string licenseNumberField;
        
        private string grossWeightField;
        
        private string workInProcessField;
        
        private string inspectionMonthField;
        
        private string odometerActualField;
        
        private string customerKeyField;
        
        private string keyToCAPExplosionDataField;
        
        private string cO2EmissionCodeField;
        
        private string registrationDateField;
        
        private string fundingExpirationDateField;
        
        private string inspectionDateField;
        
        private string driversSideField;
        
        private string freeFlooringPeriodField;
        
        private string orderedStatusField;
        
        private string publishVehicleInfoToWebField;
        
        private string saleField;
        
        private string certifiedUsedCarField;
        
        private string lastServiceDateField;
        
        private string nextServiceDateField;
        
        private VehicleLookupResponseVehicleOptionalFieldsVehicleOptionalField[] optionalFieldsField;
        
        private VehicleLookupResponseVehicleOptionsVehicleOption[] optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockNumber {
            get {
                return this.stockNumberField;
            }
            set {
                this.stockNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLApplied {
            get {
                return this.gLAppliedField;
            }
            set {
                this.gLAppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeNU {
            get {
                return this.typeNUField;
            }
            set {
                this.typeNUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessOfficeFranchiseCode {
            get {
                return this.businessOfficeFranchiseCodeField;
            }
            set {
                this.businessOfficeFranchiseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceFranchiseCode {
            get {
                return this.serviceFranchiseCodeField;
            }
            set {
                this.serviceFranchiseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ManufacturerCode {
            get {
                return this.manufacturerCodeField;
            }
            set {
                this.manufacturerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VehicleCode {
            get {
                return this.vehicleCodeField;
            }
            set {
                this.vehicleCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ModelCode {
            get {
                return this.modelCodeField;
            }
            set {
                this.modelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BodyStyle {
            get {
                return this.bodyStyleField;
            }
            set {
                this.bodyStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FuelType {
            get {
                return this.fuelTypeField;
            }
            set {
                this.fuelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MPG {
            get {
                return this.mPGField;
            }
            set {
                this.mPGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cylinders {
            get {
                return this.cylindersField;
            }
            set {
                this.cylindersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Truck {
            get {
                return this.truckField;
            }
            set {
                this.truckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FourWheelDrive {
            get {
                return this.fourWheelDriveField;
            }
            set {
                this.fourWheelDriveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Turbo {
            get {
                return this.turboField;
            }
            set {
                this.turboField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ColorCode {
            get {
                return this.colorCodeField;
            }
            set {
                this.colorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EngineCode {
            get {
                return this.engineCodeField;
            }
            set {
                this.engineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransmissionCode {
            get {
                return this.transmissionCodeField;
            }
            set {
                this.transmissionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IgnitionKeyCode {
            get {
                return this.ignitionKeyCodeField;
            }
            set {
                this.ignitionKeyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrunkKeyCode {
            get {
                return this.trunkKeyCodeField;
            }
            set {
                this.trunkKeyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeylessCode {
            get {
                return this.keylessCodeField;
            }
            set {
                this.keylessCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RadioCode {
            get {
                return this.radioCodeField;
            }
            set {
                this.radioCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WheelLockCode {
            get {
                return this.wheelLockCodeField;
            }
            set {
                this.wheelLockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DealerCode {
            get {
                return this.dealerCodeField;
            }
            set {
                this.dealerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateInInventory {
            get {
                return this.dateInInventoryField;
            }
            set {
                this.dateInInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateInService {
            get {
                return this.dateInServiceField;
            }
            set {
                this.dateInServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateDelivered {
            get {
                return this.dateDeliveredField;
            }
            set {
                this.dateDeliveredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateOrdered {
            get {
                return this.dateOrderedField;
            }
            set {
                this.dateOrderedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SaleAccount {
            get {
                return this.saleAccountField;
            }
            set {
                this.saleAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAccount {
            get {
                return this.inventoryAccountField;
            }
            set {
                this.inventoryAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DemoName {
            get {
                return this.demoNameField;
            }
            set {
                this.demoNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyMonths {
            get {
                return this.warrantyMonthsField;
            }
            set {
                this.warrantyMonthsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyMiles {
            get {
                return this.warrantyMilesField;
            }
            set {
                this.warrantyMilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarrantyDeduct {
            get {
                return this.warrantyDeductField;
            }
            set {
                this.warrantyDeductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VehicleCost {
            get {
                return this.vehicleCostField;
            }
            set {
                this.vehicleCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionPackage {
            get {
                return this.optionPackageField;
            }
            set {
                this.optionPackageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LicenseNumber {
            get {
                return this.licenseNumberField;
            }
            set {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrossWeight {
            get {
                return this.grossWeightField;
            }
            set {
                this.grossWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkInProcess {
            get {
                return this.workInProcessField;
            }
            set {
                this.workInProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InspectionMonth {
            get {
                return this.inspectionMonthField;
            }
            set {
                this.inspectionMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdometerActual {
            get {
                return this.odometerActualField;
            }
            set {
                this.odometerActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerKey {
            get {
                return this.customerKeyField;
            }
            set {
                this.customerKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeyToCAPExplosionData {
            get {
                return this.keyToCAPExplosionDataField;
            }
            set {
                this.keyToCAPExplosionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CO2EmissionCode {
            get {
                return this.cO2EmissionCodeField;
            }
            set {
                this.cO2EmissionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FundingExpirationDate {
            get {
                return this.fundingExpirationDateField;
            }
            set {
                this.fundingExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InspectionDate {
            get {
                return this.inspectionDateField;
            }
            set {
                this.inspectionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DriversSide {
            get {
                return this.driversSideField;
            }
            set {
                this.driversSideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FreeFlooringPeriod {
            get {
                return this.freeFlooringPeriodField;
            }
            set {
                this.freeFlooringPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderedStatus {
            get {
                return this.orderedStatusField;
            }
            set {
                this.orderedStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PublishVehicleInfoToWeb {
            get {
                return this.publishVehicleInfoToWebField;
            }
            set {
                this.publishVehicleInfoToWebField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sale {
            get {
                return this.saleField;
            }
            set {
                this.saleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertifiedUsedCar {
            get {
                return this.certifiedUsedCarField;
            }
            set {
                this.certifiedUsedCarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastServiceDate {
            get {
                return this.lastServiceDateField;
            }
            set {
                this.lastServiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NextServiceDate {
            get {
                return this.nextServiceDateField;
            }
            set {
                this.nextServiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VehicleOptionalField", typeof(VehicleLookupResponseVehicleOptionalFieldsVehicleOptionalField), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VehicleLookupResponseVehicleOptionalFieldsVehicleOptionalField[] OptionalFields {
            get {
                return this.optionalFieldsField;
            }
            set {
                this.optionalFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VehicleOption", typeof(VehicleLookupResponseVehicleOptionsVehicleOption), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VehicleLookupResponseVehicleOptionsVehicleOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VehicleLookupResponseVehicleOptionalFieldsVehicleOptionalField {
        
        private string optionNumberField;
        
        private string descriptionField;
        
        private string fieldTypeField;
        
        private string alphaFieldValueField;
        
        private string numericFieldValueField;
        
        private string dateFieldValueField;
        
        private string addToCostFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionNumber {
            get {
                return this.optionNumberField;
            }
            set {
                this.optionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlphaFieldValue {
            get {
                return this.alphaFieldValueField;
            }
            set {
                this.alphaFieldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumericFieldValue {
            get {
                return this.numericFieldValueField;
            }
            set {
                this.numericFieldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateFieldValue {
            get {
                return this.dateFieldValueField;
            }
            set {
                this.dateFieldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddToCostFlag {
            get {
                return this.addToCostFlagField;
            }
            set {
                this.addToCostFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VehicleLookupResponseVehicleOptionsVehicleOption {
        
        private string optionCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionCode {
            get {
                return this.optionCodeField;
            }
            set {
                this.optionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
}
