//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace OpenTrack.Definitions {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="starTransport", Namespace="http://www.starstandards.org/webservices/2005/10/transport/bindings")]
    public partial class OpenTrack : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private PayloadManifest payloadManifestValueField;
        
        private System.Threading.SendOrPostCallback ProcessMessageOperationCompleted;
        
        /// <remarks/>
        public OpenTrack() {
            this.Url = "https://opentrackqa.arkona.com/WebService.asmx";
        }
        
        public PayloadManifest PayloadManifestValue {
            get {
                return this.payloadManifestValueField;
            }
            set {
                this.payloadManifestValueField = value;
            }
        }
        
        /// <remarks/>
        public event ProcessMessageCompletedEventHandler ProcessMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PayloadManifestValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.starstandards.org/webservices/2005/10/transport/operations/ProcessMess" +
            "age", RequestNamespace="http://www.starstandards.org/webservices/2005/10/transport", ResponseNamespace="http://www.starstandards.org/webservices/2005/10/transport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProcessMessage(ref Payload payload) {
            object[] results = this.Invoke("ProcessMessage", new object[] {
                        payload});
            payload = ((Payload)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProcessMessage(Payload payload, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProcessMessage", new object[] {
                        payload}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndProcessMessage(System.IAsyncResult asyncResult, out Payload payload) {
            object[] results = this.EndInvoke(asyncResult);
            payload = ((Payload)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessMessageAsync(Payload payload) {
            this.ProcessMessageAsync(payload, null);
        }
        
        /// <remarks/>
        public void ProcessMessageAsync(Payload payload, object userState) {
            if ((this.ProcessMessageOperationCompleted == null)) {
                this.ProcessMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessMessageOperationCompleted);
            }
            this.InvokeAsync("ProcessMessage", new object[] {
                        payload}, this.ProcessMessageOperationCompleted, userState);
        }
        
        private void OnProcessMessageOperationCompleted(object arg) {
            if ((this.ProcessMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessMessageCompleted(this, new ProcessMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.starstandards.org/webservices/2005/10/transport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.starstandards.org/webservices/2005/10/transport", IsNullable=false)]
    public partial class PayloadManifest : System.Web.Services.Protocols.SoapHeader {
        
        private Manifest[] manifestField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("manifest")]
        public Manifest[] manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.starstandards.org/webservices/2005/10/transport")]
    public partial class Manifest {
        
        private string contentIDField;
        
        private string namespaceURIField;
        
        private string elementField;
        
        private string relatedIDField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string contentID {
            get {
                return this.contentIDField;
            }
            set {
                this.contentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string namespaceURI {
            get {
                return this.namespaceURIField;
            }
            set {
                this.namespaceURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relatedID {
            get {
                return this.relatedIDField;
            }
            set {
                this.relatedIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.starstandards.org/webservices/2005/10/transport")]
    public partial class Content {
        
        private System.Xml.XmlElement anyField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.starstandards.org/webservices/2005/10/transport")]
    public partial class Payload {
        
        private Content[] contentField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("content")]
        public Content[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ProcessMessageCompletedEventHandler(object sender, ProcessMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Payload payload {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Payload)(this.results[0]));
            }
        }
    }
}
